### ISSUE TITLE
dogecoind does not exempt whitelisted peers from the maxconnections limit.

### ISSUE THREAD

**Issue by crozone** [dogecoin/dogecoin#1719] opened 2021-02-09 01:23 UTC
### Describe the issue

A node that has reached its connection limit (`maxconnections`) will not accept new connections from whitelisted peers, instead logging `failed to find an eviction candidate - connection dropped (full)`.

This is problematic when trying to self-host a full public node with the intention of having other protected nodes that `connect` solely to the full node. If the public node is currently servicing too many non-whitelisted peers and has reached `maxconnections`, the private whitelisted nodes will constantly have their connections dropped.

On the Windows QT client, this manifests in the debug.log as errors like:

`socket recv error An existing connection was forcibly closed by the remote host.  (10054)`
`socket recv error An established connection was aborted by the software in your host machine.  (10053)`

This happens continuously.

The connection graph exhibits many periodic vertical red bars, which are outgoing connection attempts to the node.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:
1. Set up a full node that has a port open and will accept incoming connections. Set `maxconnections` to a low number, eg 4 or 8.
2. Add hosts to the whitelist, eg a private LAN: `whitelist=192.168.1.0/24`
3. Start the full node and wait until all of its connection slots are used
4. Start Dogecoin QT with `connect=<full node address>` in the dogecoin.conf
5. Observe that Dogecoin QT will repeatedly try and fail to connect to the full node.

### Expected behaviour
Whitelisted peers should be allowed to connect to a node regardless of `maxconnections`.

### Actual behaviour
The whitelisted peers were repeatedly dropped.

### What version of Dogecoin Core are you using?
Private node: Dogecoin Core version v1.14.2 (64-bit) Windows QT official binary / Windows 10
Public node: Dogecoin Core Daemon version v1.14.2 / Linux 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux

**Comment by patricklodder** [comment] 2021-02-09 13:50
Can you reproduce this with a higher number than 8, like 12? Because 8 is the maximum number of outgoing connections, which are also part of `maxconnections`:

https://github.com/dogecoin/dogecoin/blob/master/src/net.h#L63-L65

**Comment by crozone** [comment] 2021-02-09 23:39
That could explain it. So if the node has 8 outbound connections, it will starve `maxconnections` of being able to accept any new incoming connections?

I'm attempting to repro, should have an update in ~12 hours.

**Comment by crozone** [comment] 2021-02-14 05:48
Ok it took a while for my public node to fill up all the incoming connection spots, but I can confirm this is reproducable with 16 `maxconnections`. `getinfo` actually shows "15" connections, but nothing else can connect (including my whitelisted node).

**Comment by ReverseControl** [comment] 2021-09-03 12:19
As @patricklodder stated, maximum number of outgoing connections is also part of ``maxconnections`` which means your expectation in this issue is not accurate, i.e. the behavior you are actually getting is the expected behavior. Based on your two previous comments you now understand what is happening. I am closing this issue.

**Closed by ReverseControl** 2021-09-03 12:19 UTC
