### ISSUE TITLE
Reindexing blocks in disc (Sorry for bad grammar but I got dogecoin on spanish)

### ISSUE THREAD

**Issue by ArcherTowerZX** [dogecoin/dogecoin#1476] opened 2018-02-26 14:44 UTC
Hello all, i had a long time i didnt acsess my Dogecoin account, and I earned 50 dogecoins so I ran to claim them and when i tried to log it said something about "There are errors in blocks" and then i clicked to solve, then it started trying to sync, and it has 2 hours in there without no more, please help me, my adress is. DQJRG8Bsmecpi1y9Cqzrtf75HfkrteDofq

**Comment by langerhans** [comment] 2018-02-26 16:00
Reindexing takes a while, but you should see a progress indicator on the bottom of the Dogecoin Core main window.

**Comment by ArcherTowerZX** [comment] 2018-02-26 18:19
I see that progress but It says 4 years and 7 weeks back?

**Comment by langerhans** [comment] 2018-02-26 18:21
Yes, it will re-index the blockchain. This can happen when you e.g. cut off power from your PC without shutting it down thus corrupting the chain files. The process might take some hours depending on the speed of your PC and hard drive.  
Nothing we can fix here and no. Closing as "working as intended".

**Closed by langerhans** 2018-02-26 18:21 UTC
