### ISSUE TITLE
[feat] Doing.Only.Good.Environmentally

### ISSUE THREAD

**Issue by greenpanda69** [dogecoin/dogecoin#2182] opened 2021-05-27 04:55 UTC
# Feature Request

**Describe the Feature Request**
 I mean ,would it be impossible to ...I don’t know ... make doge coin a strong circulating currency only amongst pro-environment driven companies? Maybe this could show who is really about cleaning our home and keeping it efficient and clean for us to thrive and live and I don’t know maybe...it would be a great idea to put the necessary tool in the hands of people that really give a S*** about this beautiful rock that has gave us shelter amongst the stars , for instance, it would give the consumer at some point make a “safe environmentally concerned decision “on ether buying a V-8 monster truck for work that spews out “toxins” per mile or get something environmentally friendly and most importantly if not as good but even better a Tesla truck ...or Fords new electric truck ,basic critical thinking will only tell you where I’m going with this , at any rate I as a Native human of this beautiful planet labeled “Earth” strongly believe it is time for us to step up and clean up our mess , as to life ...we all grow up someday that’s always a hard pill to swallow, please universe take this message and express good vibration so it’s able to tune in to the right group of people that are ready to make our home (earth) green and happy again , MAKE DOGE A MULTI-PLANETARY CURRENCY, why stop here ? ....let’s set the pace with this beautiful race of human faces....I hope this is a good enough idea to raise the concern of big eggs that really care about the environment #aspergerpride

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by Ducktor8** [comment] 2021-05-27 08:35
TBH Not a feature

**Comment by rnicoll** [comment] 2021-05-27 10:37
Duplicate of #2181

**Closed by rnicoll** 2021-05-27 10:37 UTC

**Comment by greenpanda69** [comment] 2021-05-27 17:20
> TBH Not a feature

Tbh fairly new to this platform, thank you for understanding impatient being , and making a quick witted assumption
