### ISSUE TITLE
[bug] ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0)

### ISSUE THREAD

**Issue by sumariva** [dogecoin/dogecoin#3451] opened 2024-02-28 06:29 UTC
# Bug Report

**Current behavior:**
I downloaded the current version of dogecoin.
Installed and pointed to an older data folder, that has been used.
On opening, Doge showed a warning about some problem with database and asked if wanted to redo all blocks.
Just confirmed and let it begin the download of all blocks.
Some hours later, and I came back, doge has stopped on error message.
Fatal error, see debug.log.

Now, each time I restart the application, it hangs on the same problem, unable to recover.
On the splash screen, on footer, it says load complete.
I confirm the error message and the shutdown procedure complets.

**Expected behavior**
Expected the node system to recover, discard, resync with network.

**Steps to reproduce:**
I just modified the config to increase memory to 1024MiB, from the basic setup.

**Screenshots**

**Dogecoin Core version**
v1.14.6.0-3a29ba6d4, official binary

**Machine specs**
- OS: Windows 10 x64
- CPU: Intel Core i3 3217U
- RAM: 12GiB
- Disk size: 693GiB partition
- Disk Type (HD/SDD): SSD

**Extra information**
2024-02-28 06:17:53 Dogecoin version v1.14.6.0-3a29ba6d4
2024-02-28 06:17:53 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2024-02-28 06:17:53 GUI: QMetaObject::connectSlotsByName: No matching signal for on_addPeer_clicked()
2024-02-28 06:17:53 GUI: QMetaObject::connectSlotsByName: No matching signal for on_removePeer_clicked()
2024-02-28 06:17:53 GUI: QMetaObject::connectSlotsByName: No matching signal for on_testPeer_clicked()
2024-02-28 06:17:54 Assuming ancestors of block ed7d266dcbd8bb8af80f9ccb8deb3e18f9cc3f6972912680feeb37b090f8cee0 have valid signatures.
2024-02-28 06:17:54 GUI: "registerShutdownBlockReason: Successfully registered: Dogecoin Core ainda não terminou com segurança..."
2024-02-28 06:17:55 Default data directory C:\Users\sumar\AppData\Roaming\Dogecoin
2024-02-28 06:17:55 Using data directory E:\Moedas\Doge
2024-02-28 06:17:55 Set backupdir "E:\Moedas\Doge\backups"
2024-02-28 06:17:55 Using backup directory E:\Moedas\Doge\backups
2024-02-28 06:17:55 Using config file E:\Moedas\Doge\dogecoin.conf
2024-02-28 06:17:55 Using at most 125 automatic connections (2048 file descriptors available)
2024-02-28 06:17:55 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2024-02-28 06:17:55 Using 4 threads for script verification
2024-02-28 06:17:55 Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
2024-02-28 06:17:55 Using wallet wallet.dat
2024-02-28 06:17:55 init message: Verificando carteira...
2024-02-28 06:17:55 CDBEnv::Open: LogDir=E:\Moedas\Doge\database ErrorFile=E:\Moedas\Doge\db.log
2024-02-28 06:17:55 scheduler thread start
2024-02-28 06:17:55 Bound to [::]:22556
2024-02-28 06:17:55 Bound to 0.0.0.0:22556
2024-02-28 06:17:55 Cache configuration:
2024-02-28 06:17:55 * Using 2.0MiB for block index database
2024-02-28 06:17:55 * Using 8.0MiB for chain state database
2024-02-28 06:17:55 * Using 1014.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2024-02-28 06:17:55 init message: Carregando índice de blocos...
2024-02-28 06:17:55 Opening LevelDB in E:\Moedas\Doge\blocks\index
2024-02-28 06:17:55 Opened LevelDB successfully
2024-02-28 06:17:55 Using obfuscation key for E:\Moedas\Doge\blocks\index: 0000000000000000
2024-02-28 06:17:55 Opening LevelDB in E:\Moedas\Doge\chainstate
2024-02-28 06:17:56 Opened LevelDB successfully
2024-02-28 06:17:56 Using obfuscation key for E:\Moedas\Doge\chainstate: d605637c1b606458
2024-02-28 06:18:27 LoadBlockIndexDB: last block file = 18
2024-02-28 06:18:27 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=5693, size=131648580, heights=105392...111638, time=2014-02-18...2014-02-22)
2024-02-28 06:18:27 Checking all blk files are present...
2024-02-28 06:18:31 LoadBlockIndexDB: transaction index disabled
2024-02-28 06:18:31 LoadBlockIndexDB: hashBestChain=bae7238a94277da107ede936a21a93979cd38565f2e5b8e7431bb2b4c1d5919d height=111441 date=2014-02-22 05:26:01 progress=0.078501
2024-02-28 06:18:31 init message: Reanalizando blocos...
2024-02-28 06:18:32 init message: Verificando blocos...
2024-02-28 06:18:32 Verifying last 6 blocks at level 3
2024-02-28 06:18:32 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2024-02-28 06:18:32 No coin database inconsistencies in last 7 blocks (79 transactions)
2024-02-28 06:18:32  block index           37369ms
2024-02-28 06:18:32 init message: Carregando carteira...
2024-02-28 06:18:32 nFileVersion = 1140600
2024-02-28 06:18:32 Keys: 103 plaintext, 0 encrypted, 103 w/ metadata, 103 total
2024-02-28 06:18:32  wallet                   27ms
2024-02-28 06:18:32 setKeyPool.size() = 100
2024-02-28 06:18:32 mapWallet.size() = 0
2024-02-28 06:18:32 mapAddressBook.size() = 2
2024-02-28 06:18:32 mapBlockIndex.size() = 1989662
2024-02-28 06:18:32 nBestHeight = 111441
2024-02-28 06:18:32 ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0)
2024-02-28 06:18:32 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=18, nPos=126585335)
2024-02-28 06:18:32 *** Failed to read block
2024-02-28 06:18:32 torcontrol thread start
2024-02-28 06:18:33 init message: Carregando endereços...
2024-02-28 06:18:33 Loaded 58240 addresses from peers.dat  588ms
2024-02-28 06:18:33 init message: Carregando lista de banidos...
2024-02-28 06:18:33 init message: Iniciando análise da rede...
2024-02-28 06:18:33 net thread start
2024-02-28 06:18:33 dnsseed thread start
2024-02-28 06:18:33 addcon thread start
2024-02-28 06:18:33 opencon thread start
2024-02-28 06:18:33 init message: Carregamento terminado!
2024-02-28 06:18:33 msghand thread start
2024-02-28 06:18:44 Loading addresses from DNS seeds (could take a while)
2024-02-28 06:18:45 25 addresses found from DNS seeds
2024-02-28 06:18:45 dnsseed thread exit
2024-02-28 06:20:11 Failed to connect best blockImported mempool transactions from disk: 0 successes, 0 failed, 0 expired
2024-02-28 06:20:11 tor: Thread interrupt
2024-02-28 06:20:11 torcontrol thread exit
2024-02-28 06:20:11 addcon thread exit
2024-02-28 06:20:11 opencon thread exit
2024-02-28 06:20:11 scheduler thread interrupt
2024-02-28 06:20:11 Shutdown: In progress...
2024-02-28 06:20:11 net thread exit
2024-02-28 06:20:11 msghand thread exit
2024-02-28 06:20:12 Shutdown: done

**Comment by patricklodder** [comment] 2024-02-28 13:43
This looks like corrupted block data from a 1.4 or earlier client (there's never been a valid `version=0` block). 

If you don't mind re-downloading 111k blocks:

1. shut down
2. back up the entire `datadir` somewhere safe
3. from your live datadir, remove the `blocks` and `chainstate` folders
4. restart

**Comment by sumariva** [comment] 2024-02-28 15:39
OK, emptied folders.
Deleted the debug.log.

At the new debug.log I see this entry:
> Using config file E:\Moedas\Doge\dogecoin.conf

but this file does not exist on the folder. Maybe tried to say that it would check if the file exists and load it.
I also noted some messages have been translated into local language and others have been writeen in English.
Need help about translating?

I see few connections(peers), most time about 6 to 10 connections. It uses less than 10% of bandwidth, and about 30% CPU on a 2 core + 4 threads CPU. Not even the disk usage hit max.
There is any configuration to allow more peers or concurrency, to speed up?

**Comment by patricklodder** [comment] 2024-02-28 18:57
>  Maybe tried to say that it would check if the file exists and load it.

Correct, we should change that message.

> I also noted some messages have been translated into local language and others have been writeen in English.
Need help about translating?

Always can use help. Which language are you using? 

> There is any configuration to allow more peers or concurrency, to speed up?

The 30% on a 4-thread CPU makes sense. Most validation has to be done serially (due to the "chain" element) and therefore on uses a single thread. Once you get past the `assumeutxo` value, everything will be used because script validation takes place in parallel.

**Comment by sumariva** [comment] 2024-02-29 02:11
OK, my language is pt_BR.

The same machine also has a Bitcoin node running, stored on the same partition. A few times my notebook hanged, but after restarting, the bitcoin always checks blocks and keep it from the last point.
Expected the doge to be more robust.

Today, the problem happened again. But today I got a screen capture before closing it.
What is weird, is that dogecoing is unable to discard the block or database record to the last correct and restart over.
It has been running for more than 8 hours. 
And the machine did not stop after doge hung, I took the screenshot, wrote this e-mail, and much more.
I guess this is not a hardware fault. I used this notebook all day.
The new entry at debug, I guess it rotated the log, because the initial lines were out of log file, that has about 10MiB in size:

2024-02-29 01:30:01 UpdateTip: new best=edcaa545fea126d7d9e5ab31e287be4c060e65089890c21324d9644ad80a5ae1 height=133236 version=0x00000002 log2_work=58.588442 tx=8450789 date='2014-03-09 14:18:43' progress=0.083361 cache=558.6MiB(2980736tx)
2024-02-29 01:30:01 UpdateTip: new best=9b5538fbb1417b0f2e23e37c94f373924b475cd9926af8c57b308663954cf851 height=133237 version=0x00000002 log2_work=58.588454 tx=8450809 date='2014-03-09 14:19:24' progress=0.083361 cache=558.6MiB(2980745tx)
2024-02-29 01:30:01 ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0)
2024-02-29 01:30:01 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=21, nPos=94173498)
2024-02-29 01:30:01 *** Failed to read block
2024-02-29 01:48:55 ERROR: ProcessNewBlock: ActivateBestChain failed
2024-02-29 01:48:55 tor: Thread interrupt
2024-02-29 01:48:55 torcontrol thread exit
2024-02-29 01:48:55 addcon thread exit
2024-02-29 01:48:55 opencon thread exit
2024-02-29 01:48:55 scheduler thread interrupt
2024-02-29 01:48:55 Shutdown: In progress...
2024-02-29 01:48:56 ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0)
2024-02-29 01:48:56 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=21, nPos=94173498)
2024-02-29 01:48:56 *** Failed to read block
2024-02-29 01:48:59 ERROR: ProcessNewBlock: ActivateBestChain failed
2024-02-29 01:48:59 net thread exit
2024-02-29 01:48:59 msghand thread exit
2024-02-29 01:48:59 Dumped mempool: 0s to copy, 0.015624s to dump
2024-02-29 01:49:33 Shutdown: done
2024-02-29 01:51:27 



2024-02-29 01:51:27 Dogecoin version v1.14.6.0-3a29ba6d4
2024-02-29 01:51:27 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2024-02-29 01:51:27 GUI: QMetaObject::connectSlotsByName: No matching signal for on_addPeer_clicked()
2024-02-29 01:51:27 GUI: QMetaObject::connectSlotsByName: No matching signal for on_removePeer_clicked()
2024-02-29 01:51:27 GUI: QMetaObject::connectSlotsByName: No matching signal for on_testPeer_clicked()
2024-02-29 01:51:27 Assuming ancestors of block ed7d266dcbd8bb8af80f9ccb8deb3e18f9cc3f6972912680feeb37b090f8cee0 have valid signatures.
2024-02-29 01:51:27 GUI: "registerShutdownBlockReason: Successfully registered: Dogecoin Core ainda não terminou com segurança..."
2024-02-29 01:51:29 Default data directory C:\Users\sumar\AppData\Roaming\Dogecoin
2024-02-29 01:51:29 Using data directory E:\Moedas\Doge
2024-02-29 01:51:29 Set backupdir "E:\Moedas\Doge\backups"
2024-02-29 01:51:29 Using backup directory E:\Moedas\Doge\backups
2024-02-29 01:51:29 Using config file E:\Moedas\Doge\dogecoin.conf
2024-02-29 01:51:29 Using at most 125 automatic connections (2048 file descriptors available)
2024-02-29 01:51:29 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2024-02-29 01:51:29 Using 4 threads for script verification
2024-02-29 01:51:29 Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
2024-02-29 01:51:29 scheduler thread start
2024-02-29 01:51:29 Using wallet wallet.dat
2024-02-29 01:51:29 init message: Verificando carteira...
2024-02-29 01:51:29 CDBEnv::Open: LogDir=E:\Moedas\Doge\database ErrorFile=E:\Moedas\Doge\db.log
2024-02-29 01:51:30 Bound to [::]:22556
2024-02-29 01:51:30 Bound to 0.0.0.0:22556
2024-02-29 01:51:30 Cache configuration:
2024-02-29 01:51:30 * Using 2.0MiB for block index database
2024-02-29 01:51:30 * Using 8.0MiB for chain state database
2024-02-29 01:51:30 * Using 1014.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2024-02-29 01:51:30 init message: Carregando índice de blocos...
2024-02-29 01:51:30 Opening LevelDB in E:\Moedas\Doge\blocks\index
2024-02-29 01:51:59 Opened LevelDB successfully
2024-02-29 01:51:59 Using obfuscation key for E:\Moedas\Doge\blocks\index: 0000000000000000
2024-02-29 01:51:59 Opening LevelDB in E:\Moedas\Doge\chainstate
2024-02-29 01:52:42 Opened LevelDB successfully
2024-02-29 01:52:42 Using obfuscation key for E:\Moedas\Doge\chainstate: a079c6d1e405724b
2024-02-29 01:53:57 LoadBlockIndexDB: last block file = 21
2024-02-29 01:53:57 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=7925, size=99674080, heights=125598...133822, time=2014-03-04...2014-03-09)
2024-02-29 01:53:57 Checking all blk files are present...
2024-02-29 01:54:01 LoadBlockIndexDB: transaction index disabled
2024-02-29 01:54:01 LoadBlockIndexDB: hashBestChain=9b5538fbb1417b0f2e23e37c94f373924b475cd9926af8c57b308663954cf851 height=133237 date=2014-03-09 14:19:24 progress=0.083361
2024-02-29 01:54:01 init message: Reanalizando blocos...
2024-02-29 01:54:03 init message: Verificando blocos...
2024-02-29 01:54:03 Verifying last 6 blocks at level 3
2024-02-29 01:54:03 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2024-02-29 01:54:03 No coin database inconsistencies in last 7 blocks (134 transactions)
2024-02-29 01:54:03  block index          153938ms
2024-02-29 01:54:03 init message: Carregando carteira...
2024-02-29 01:54:03 nFileVersion = 1140600
2024-02-29 01:54:03 Keys: 103 plaintext, 0 encrypted, 103 w/ metadata, 103 total
2024-02-29 01:54:03  wallet                   31ms
2024-02-29 01:54:03 setKeyPool.size() = 100
2024-02-29 01:54:03 mapWallet.size() = 0
2024-02-29 01:54:03 mapAddressBook.size() = 2
2024-02-29 01:54:03 mapBlockIndex.size() = 4928001
2024-02-29 01:54:03 nBestHeight = 133237
2024-02-29 01:54:03 ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0)
2024-02-29 01:54:03 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=21, nPos=94173498)
2024-02-29 01:54:03 *** Failed to read block
2024-02-29 01:54:03 torcontrol thread start
2024-02-29 01:54:04 init message: Carregando endereços...
2024-02-29 01:54:04 Loaded 55675 addresses from peers.dat  415ms
2024-02-29 01:54:04 init message: Carregando lista de banidos...
2024-02-29 01:54:04 init message: Iniciando análise da rede...
2024-02-29 01:54:04 net thread start
2024-02-29 01:54:04 dnsseed thread start
2024-02-29 01:54:04 addcon thread start
2024-02-29 01:54:04 opencon thread start
2024-02-29 01:54:04 msghand thread start
2024-02-29 01:54:04 init message: Carregamento terminado!
2024-02-29 01:54:07 Failed to connect best blockImported mempool transactions from disk: 0 successes, 0 failed, 0 expired
2024-02-29 01:54:07 tor: Thread interrupt
2024-02-29 01:54:07 addcon thread exit
2024-02-29 01:54:07 torcontrol thread exit
2024-02-29 01:54:07 dnsseed thread exit
2024-02-29 01:54:07 scheduler thread interrupt
2024-02-29 01:54:07 Shutdown: In progress...
2024-02-29 01:54:07 msghand thread exit
2024-02-29 01:54:07 net thread exit
2024-02-29 01:54:09 opencon thread exit
2024-02-29 01:54:10 Shutdown: done

![doge-fatal-error](https://github.com/dogecoin/dogecoin/assets/6371372/39b4fdda-8f7e-4e8e-9839-98b30ec0ea79)

**Comment by patricklodder** [comment] 2024-02-29 03:10
Thanks. This is indeed odd. What I'm investigating: what would need to happen for it be possible to write a header to disk (because it errors on `ReadBlockFromDisk`), without prior validation.

**Comment by patricklodder** [comment] 2024-02-29 13:53
I've gone through every code path 3 times now and under normal operation there is no situation that I can find in which a header that has version 0 can get accepted (and subsequently added to the index and written to disk as such).

Is it possible that the machine you're doing this on gets suspended during sync, or that it is excessively using swap?

**Comment by sumariva** [comment] 2024-02-29 18:19
Not suspended and also with low swap. But the partition I have been using to store the blocks, is using a new driver, btrfs.
This is a kind new partition scheme from Linux ported to Windows.
I using it because the native filesystem compression is good to save space, about 15 to 20%. Much more effective then NTFS compression.
But today I got the bitcoin client reporting out of space.
During check, there has been a discrepancy of reported free space.
The filesystem check did not report errors.

I will repeat the test on a NTFS partition.
I filled a report on the driver's project about this situation: https://github.com/maharmstone/btrfs/issues/632

Maybe some corrupted data on low level driver, but I have been using this partition with bitcoin for 2 weeks without problems.
Alos some movies and games are working fine.

**Comment by sumariva** [comment] 2024-03-23 20:46
To give you update. Dogecoin finally syncronized.
I moved the data directory again to the experimental partition btrfs. But now, I pruned the node.
For more than a week, I have been opening the wallet and no more issues.
So, for while, for this report, the only thing that can be updated are:
- when this message shows up, forward to the same code that popup the corrupted and rebuild dialog. 
Because, now, when this message turns out, it is impossible to make actions from the GUI.

- create a tool to try recovery up to last stable block
The wallet is quite slow to sync, so having some recovery mode, to try save or rollback to last stable block, would be nice.

**Comment by patricklodder** [comment] 2024-03-25 00:07
I have translated your findings into a feature request at #3489 - I think these are good suggestions.

I'm going to label this bug report as `external` (because this seems to have been caused by a disk driver issue) and close it for now. We can open it later if it happens again for you or someone else and we suspect something else causes this.

**Closed by patricklodder** 2024-03-25 00:07 UTC
Labels: external
