### ISSUE TITLE
[bug] debug.log shows "Error -30973, can't open database wallet.dat" and "BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery"

### ISSUE THREAD

**Issue by negatratoron** [dogecoin/dogecoin#3059] opened 2022-07-21 13:02 UTC
# Dogecoin Core crashes, much gasp!

**Current behavior:**
After leaving Dogecoin Core open for a period of hours, a popup says: An error occurred.  Please check debug.log.

Then Dogecoin Core exits.

**Expected behavior**
Dogecoin continues to run, and does not crash

**Steps to reproduce:**
Just run Dogecoin Core on Windows 10

**Dogecoin Core version**
v1.14.5.0-31afad1331

**Machine specs**
- OS: Windows 10
- CPU: 12th Gen Intel Core i7-12700K
- RAM: 32 GB
- Disk size: 3 TB, >500GB free
- Disk Type (HD/SDD): HD

**Extra information**
Last bit of debug.log:

```
2022-07-21 12:53:05 UpdateTip: new best=4e220b065e53bacbc6e4fc8c2862907cf4dddb6db8ae98cc34f10bf2c570593d height=4315848 version=0x00620104 log2_work=74.986531 tx=87062081 date='2022-07-21 12:52:52' progress=1.000000 cache=177.5MiB(187906tx)
2022-07-21 12:53:31 receive version message: /blockchair.com/dogecoin/nodes/: version 70015, blocks=4315844, us=[2603:3016:1e01:b9a0:1d00:4d4e:ee11:d93b]:22556, peer=32
2022-07-21 12:53:38 UpdateTip: new best=2a5ebc7ab46a71182601162007db3d86ae7ae5fb99b9b0969a40963e4284ae24 height=4315849 version=0x00620104 log2_work=74.986531 tx=87062097 date='2022-07-21 12:53:05' progress=1.000000 cache=177.5MiB(187919tx)
2022-07-21 12:53:40 socket recv error An existing connection was forcibly closed by the remote host.  (10054)
2022-07-21 12:53:41 receive version message: Shibetoshi:1.14.5: version 70016, blocks=8613396, us=[2603:3016:1e01:b9a0:1d00:4d4e:ee11:d93b]:22556, peer=33
2022-07-21 12:53:52 Misbehaving: [2400:6180:100:d0::94a:5001]:49752 peer=33 (0 -> 1)
2022-07-21 12:53:52 ProcessMessages(sendaddrv2, 0 bytes) FAILED peer=33
2022-07-21 12:54:39 *** System error while flushing: CDB: Error -30973, can't open database wallet.dat
2022-07-21 12:54:44 *** System error while flushing: CDB: Error -30973, can't open database wallet.dat
2022-07-21 12:54:44 tor: Thread interrupt
2022-07-21 12:54:44 opencon thread exit
2022-07-21 12:54:44 addcon thread exit
2022-07-21 12:54:44 torcontrol thread exit
2022-07-21 12:54:44 net thread exit
2022-07-21 12:54:44 scheduler thread interrupt
2022-07-21 12:54:44 Shutdown: In progress...
2022-07-21 12:54:44 msghand thread exit
2022-07-21 12:54:44 Dumped mempool: 0s to copy, 0.040114s to dump
2022-07-21 12:54:45 *** System error while flushing: CDB: Error -30973, can't open database wallet.dat
2022-07-21 12:54:47 CDBEnv::EnvShutdown: Error -30973 shutting down database environment: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
2022-07-21 12:54:47 Shutdown: done
```

**Comment by patricklodder** [comment] 2022-07-21 14:13
Hi. In your data directory (where you got the debug.log from) there are (probably) 2 interesting log locations:

- `db.log`
- `database/log.xxxxxx` (optionally)

Could you please share the contents of these log files with us?

**Comment by negatratoron** [comment] 2022-07-21 14:24
Here are the files.

[db.log](https://github.com/dogecoin/dogecoin/files/9160117/db.log)
[log.0000000001.txt](https://github.com/dogecoin/dogecoin/files/9160120/log.0000000001.txt)

**Comment by patricklodder** [comment] 2022-07-21 15:01
What it seems to be "panicking" about is that the `log.000000001` file does not match the `wallet.dat` file - did you recently replace the `wallet.dat` from a previous installation?

**Comment by patricklodder** [comment] 2022-07-21 15:52
I'd recommend the following:

1. completely shut down Dogecoin Core (make sure in the task manager that there is no dogecoin-qt.exe running at all)
2. make a backup of `wallet.dat` outside of the data directory
3. rename the `database` folder to `database.old`
4. restart dogecoin core.

if that doesn't work, I have some other options for you, but let's try this first. No need to close the issue before we solve it ❤️

**Comment by negatratoron** [comment] 2022-07-21 17:26
It seems like Dogecoin Core actually deletes the `database` folder when I exit it.  (I don't 100% remember, but I must have had Dogecoin Core opened when I sent you the `log.000000001` file.)  So I don't think that makes any effective changes to my environment.

Dogecoin Core does crash and ask me to open debug.log when I exit it.  The last few lines are identical to what I posted originally: "can't open database wallet.dat" followed by "BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery".

**Comment by patricklodder** [comment] 2022-07-21 18:25
I tried finding you a windows pre-compiled version of db_recover.exe but all the sites that host it look shady (and I cannot seem to find an oracle 5.3.28NC release), so let's not. I'll look into compiling it.

**Comment by patricklodder** [comment] 2022-07-22 16:11
Still working on cross-compiling the toolset but it looks like I'm getting somewhere finally - apologies for slow progress on this.

I'll document and publish what I did and will provide tools to reproduce the files. Am first going to have to test what I have so far before messing up your wallet. Thank you for your patience!

**Comment by negatratoron** [comment] 2022-07-22 19:28
No problem, take your time!

**Comment by patricklodder** [comment] 2022-07-29 20:50
@negatratoron, please see below for the best possible solution I think I can offer:

0. Stop ALL instances of dogecoin - check in process explorer that no `dogecoind` or `dogecoin-qt` processes are running
1. Either [build your own bdb tools for win64](https://gist.github.com/patricklodder/d3e16ce97ace16f2045f829901974ccc) if you can, or [download the ones I built](https://plddr.s3.eu-central-1.amazonaws.com/bdb_tools.zip) if you cannot.
2. unzip the `bdb_tools.zip` somewhere convenient
3. back up your `wallet.dat`
4. **copy** the backed up wallet to the same place you unzipped the tools, call it something smart, like `wallet.corrupt.dat`
5. open a command prompt and navigate to the place where your wallet and the tools are
6. dump contents into a text file, guard that textile with your life just like you would for your wallet: `db_dump -r -f wallet.dump wallet.dat`
7. load the textile into a new wallet.dat file: `db_load -f wallet.dump wallet.new.dat` and **delete the textfile (!!!)**
8. delete the `database` directory and of course `wallet.dat` from your dogecoin data directory
9. copy `wallet.new.dat` into the dogecoin data directory and call it `wallet.dat`
10. start your Dogecoin software

If you're having any trouble with balances not showing up AND this is an HD wallet (i.e. created with a version > 1.14.0), please, when using 1.14.6, go to the debug console, type: `rescan 1` and wait an hour or so for it to process everything.

Please let us know whether this worked. ❤️

**Comment by negatratoron** [comment] 2022-08-10 07:31
@patricklodder Sorry it took me so long to get back to you, but it looks like those steps worked.

As I first mentioned in [this comment](https://github.com/dogecoin/dogecoin/issues/3059#issuecomment-1191751150), Dogecoin Core also gave that error when I closed it, however now I can close it without the error occurring.  For that reason, it seems likely to me that it's fixed and Dogecoin Core won't crash when left open either.

Thanks!

**Comment by patricklodder** [comment] 2022-08-22 16:16
@negatratoron thank you for letting us know. I am closing the issue.

**Closed by patricklodder** 2022-08-22 16:16 UTC
