### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by ryanthelion69** [dogecoin/dogecoin#2088] opened 2021-05-25 10:04 UTC
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

Practical Ideas for Dogecoin Developers from a former Econ Major:

Step 1: Limit influx of new dogecoins to create some scarcity in the market-
Dogecoin can not reach the moon if more and more coins constantly enter the market, scarcity drives value and everyone here wants to see dogecoins value go up. Furthermore, there’s already a lot of coins out there already, give the people a chance to buy and hodl
Example of how this doesn’t work: Zimbabwe currency crisis and the Weimar Republic economic crisis

Step 2: Use social media and technology to update the public on important changes- 
Making the public more aware of changes helps raise value, especially if those are positive changes. Public awareness of the changing nature of Dogecoin will help better educate future holders on our path to the moon

Step 3: Improve privacy of transactions and implement security features to prevent fraud or scams-
Part of what is appealing about cryptocurrency is that block chains add to security and privacy. Other currencies like Monero use safeguards to ensure that people can’t do crypto scams by promising a good or service and then not following through. Furthermore, Dogecoin wallets should be secure and private in order to compete with Bitcoin, Ethereum, and Monero in the eyes of the greater crypto subcultures.

Step 4: Create a crypto wallet app(both apple and google play) for Dogecoin which allows users to buy/sell Dogecoin, receive Dogecoin as payment and spend Dogecoin for goods and services-
Adding the security and privacy features from above will guarantee great success. This will also reduce usage of whales such as Robinhood aka Robin-Da-Hood. 

Step 5: Upvote, add ideas in the comments and try to get the development team’s attention to implement these ideas-
Thanks for your time let’s go to the moon!

**Comment by a2br** [comment] 2021-05-25 11:53
Hey! You should rename the issue, I'm sure it'll help the people who manage the Issues' life easier.

**Comment by AbcSxyZ** [comment] 2021-05-25 11:59
**Step 1** : Duplicate of duplicate (#2003). In seven year, you're not the first to suggest it :)

**Step 2** : Totally agree, I don't know the position of core devs but in any case the dogecoin project is open source. The open source movement promote transparency and democratic process to make decision. It's not actually perfect, but it's probably a horizon !

**Step 3** : Privacy is a huge concern, and there is a lot to discuss. But it's limited by the technology, everyone sharing the blockchain file, the ledger, and this information is public, and it's needed to be public. You can be anonymous, but it's becoming harder and harder (exchange verify your identities for example). Big dilemma for a lot of cryptos, hard to solve.
If you want, there is a Snowden interview (see [podcast](https://www.youtube.com/watch?v=AcWcusXqClo) or [full interview](https://www.youtube.com/watch?v=JRsvz6pRtZE)).

**Step 4** : [If anyone know existing client for apple or android, do not hesitate to share]
For the moment if it can help, as a web client, you can have [dogechain.info](https://dogechain.info/) if you use an exchange who don't let you have a wallet (aka Robinhood).
Some community apps should come soon, see #2011 for example. This kind of application will mainly come from outside.

**Comment by alamshafil** [comment] 2021-05-25 12:09
I believe there already is a Dogecoin android app: [https://play.google.com/store/apps/details?id=de.langerhans.wallet](https://play.google.com/store/apps/details?id=de.langerhans.wallet)

**Comment by patricklodder** [comment] 2021-05-25 15:59
Closing this per #2110, point 8.

**Closed by patricklodder** 2021-05-25 15:59 UTC
