### ISSUE TITLE
[feat] Update `ltc_scrypt` python module

### ISSUE THREAD

**Issue by rllola** [dogecoin/dogecoin#2656] opened 2021-11-01 17:13 UTC
# Feature Request

**Describe the Feature Request**

The python script used for test is required a old python scrypt module. This modules doesn't look compatible with python3 (unless I am doing it wrong).

**Describe Preferred Solution**

Replace it by a python3 module like `litecoin_scrypt` (https://pypi.org/project/litecoin_scrypt/).
It is basically the same code but updated for python3. It keeps the same function name too.

**Related Code**

See
https://github.com/dogecoin/dogecoin/blob/master/qa/rpc-tests/test_framework/scrypt_auxpow.py#L16

I have been using some of the code for test purpose and replaced it by this python3 compatible scrypt lib. It worked great for me.
https://github.com/rllola/dogecoin-miner-rust/blob/feature/support-merge-mining/script/scrypt_auxpow.py

**Additional Context**

Python2 has been deprecated and it can be a bit of a headache if we need to install it in order to have this lib working. Updating it would make it a little bit easier for testing.

Those python tests are also a great starting point for dev who need to generate working outputs for debugging or testing. Being able to run it with the minimum amount of frustration is nice.

**Comment by patricklodder** [comment] 2021-11-01 17:18
It works for me with python3, do you run `qa/pull-tester/install-deps.sh`? or try to use package manager?

**Comment by rllola** [comment] 2021-11-01 17:23
I tried using `pip install ltc_scrypt`

This is the error message:
```
Collecting ltc_scrypt
  Using cached ltc_scrypt-1.0.tar.gz (7.0 kB)
Building wheels for collected packages: ltc-scrypt
  Building wheel for ltc-scrypt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ikgg4ici/ltc-scrypt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ikgg4ici/ltc-scrypt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_skm1yu1
       cwd: /tmp/pip-install-ikgg4ici/ltc-scrypt/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ltc_scrypt' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./ltc_scrypt -I/usr/include/python3.8 -c ./scryptmodule.c -o build/temp.linux-x86_64-3.8/./scryptmodule.o
  ./scryptmodule.c: In function ‘scrypt_getpowhash’:
  ./scryptmodule.c:9:5: error: unknown type name ‘PyStringObject’; did you mean ‘PySliceObject’?
      9 |     PyStringObject *input;
        |     ^~~~~~~~~~~~~~
        |     PySliceObject
  ./scryptmodule.c:15:5: warning: implicit declaration of function ‘scrypt_1024_1_1_256’ [-Wimplicit-function-declaration]
     15 |     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
        |     ^~~~~~~~~~~~~~~~~~~
  ./scryptmodule.c:15:33: warning: implicit declaration of function ‘PyString_AsString’ [-Wimplicit-function-declaration]
     15 |     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
        |                                 ^~~~~~~~~~~~~~~~~
  ./scryptmodule.c:15:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     15 |     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
        |                         ^
  ./scryptmodule.c: In function ‘initltc_scrypt’:
  ./scryptmodule.c:28:12: warning: implicit declaration of function ‘Py_InitModule’ [-Wimplicit-function-declaration]
     28 |     (void) Py_InitModule("ltc_scrypt", ScryptMethods);
        |            ^~~~~~~~~~~~~
  ./scryptmodule.c:29:1: warning: control reaches end of non-void function [-Wreturn-type]
     29 | }
        | ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ltc-scrypt
```

**Comment by patricklodder** [comment] 2021-11-01 17:32
Ah yes, please use the provided script. It compiles from source.

**Comment by rllola** [comment] 2021-11-01 17:46
I am really confused now...

I don't understand why I can install `litecoin_scrypt` using `pip install` but for `ltc_scrypt` it only works by doing `python3 setup.py install`.

The two libraries are the same except for the binding.

**Comment by patricklodder** [comment] 2021-11-01 17:51
The install script installs a verified source (by us), pip does not. We can change sources in a next release to also support the pip version and switch to a verified tag in whatever the source for the published `litecoin_scrypt` module is. That will solve your problem. For now though, the way to use the regression test suite is by running the supplied dependency install script. That's also what the CI does.

Is targeting this for 1.14.6 ok with you?

**Comment by rllola** [comment] 2021-11-01 18:19
Ok I just understand what is the difference.

The one published here : https://github.com/langerhans/ltc-scrypt/archive/master.tar.gz
is the same as `litecoin_scrypt` but with the old module name `ltc_scrypt`.

I though you were running the test using python2 because I was looking for the package in pip. You are not tho.

> Is targeting this for 1.14.6 ok with you?
That sounds good. It is really low priority tho. So you can even close this.

**Comment by patricklodder** [comment] 2021-11-01 18:25
Let's just fix it - it has been a source of confusion for forever...

**Comment by micaelmalta** [comment] 2022-02-08 23:41
@rllola @patricklodder FYI, litecoin_scrypt from pip doesn't provide the same results for `getPoWHash` as ltc_scrypt

**Comment by vertiond** [comment] 2022-03-26 05:02
https://github.com/langerhans/ltc-scrypt/pull/1

**Comment by chromatic** [comment] 2022-06-20 00:28
@langerhans There's still a chance we could get this into 1.14.6, but we might have to reschedule it for 1.14.7. That's not a bad thing; the dep-installer script works just fine now.

**Comment by patricklodder** [comment] 2022-07-14 14:35
Rescheduled for 1.14.7

**Comment by patricklodder** [comment] 2022-07-27 01:42
This is becoming more urgent - the dependency no longer compiles with Python 3.10 that is shipped with Ubuntu 22.04 due to this error:

```
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by chromatic** [comment] 2023-04-29 15:57
With #3080 merged, can we close this issue?

**Comment by xanimo** [comment] 2023-04-30 00:30
> With #3080 merged, can we close this issue?

sgtm

**Closed** 2023-05-01 10:27 UTC
Labels: enhancement
