### ISSUE TITLE
How to redeem doge coin back from output with private key

### ISSUE THREAD

**Issue by doge0901** [dogecoin/dogecoin#1419] opened 2018-01-05 09:47 UTC
Hi,
please help me to redeem the coins back.
I have windows 10 (64bit) with Dogecoin Core QT 1.10 wallet
After I made 2 transactions ( wallet was not entirely  completed to sync ) 6 and 100000, wallet made other 2 transactions for no reason https://dogechain.info/address/DQeNuxSRGCHFLXGZG5nzo1RWBD9RnTW8cP
transaction https://dogechain.info/tx/6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3
Amount I sent only 100000 6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3-001
How I got other amount-381,251.01927000 sent ?   
Please help me to retrieve it.
Thank you

PS: I Synchronized it completely and than re-index it with no luck to show balance correct.
 I did not do anything with wallet.dat except encrypted it with new passphrase since I restored it from unencrypted usb flash which I kept it as a back up.
It is synchronized fully
I do no have such address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 after I did dumpwallet and printed to find it.
This is really weird. Any other suggestions to reedem it?
Thank you.

**Comment by rnicoll** [comment] 2018-01-05 10:30
Sounds like you're seeing the change: https://en.bitcoin.it/wiki/Change

The address it's paid the 381,251.01927000 to should be one the wallet owns, not sure why it's not showing up in the client. You haven't done anything with your `wallet.dat` as part of this have you?

**Comment by langerhans** [comment] 2018-01-05 10:31
The wallet didn't send any transaction "for now reason". It just sent the change back into a change address that is part of your wallet. Just let the wallet sync fully and the coins will show up.

**Comment by doge0901** [comment] 2018-01-05 11:30
I did not do anything with wallet.dat except encrypted it with new passphrase since I restored it from unencrypted usb flash which I kept it as a back up. 
It is synchronized fully 
I do no have such address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4  after I did dumpwallet and printed to find it.
This is really weird. Any other suggestions to reedem it?
Thank you.
![dogecoincoreqt 1-5-18](https://user-images.githubusercontent.com/35134142/34607107-b15d3072-f1d7-11e7-90ad-a85e289bbe4a.JPG)

**Comment by doge0901** [comment] 2018-01-05 20:17
Any ideas what to do next?

**Comment by langerhans** [comment] 2018-01-05 20:30
Try starting the wallet with the `-rescan` parameter and see if that fixes it.

**Comment by doge0901** [comment] 2018-01-06 17:23
No, it did not help.
It looks like this is not even my address  after I ran command validateaddress command ther is an outpu:
11:17:32
￼validateaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4
11:17:33
￼{
"isvalid" : true,
"address" : "DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4",
"scriptPubKey" : "76a9146d1bd1917c91ea48041d04d2d42ec4e11aac689788ac",
"ismine" : false,
"iswatchonly" : true,
"isscript" : false,
"account" : ""
}

Is any way way to restore it xprv keyfrom wallet.dat and script discussed in https://github.com/prusnak/bip32utils
By the way i can not find xprv key after dumwallet command in file either.
thanks

**Comment by doge0901** [comment] 2018-01-06 17:42
![dogecoincoreqt 1-6-18](https://user-images.githubusercontent.com/35134142/34642289-47d3eb8c-f2d6-11e7-8e39-3123dc99be83.JPG)

**Comment by langerhans** [comment] 2018-01-06 17:56
Post a screenshot of your transaction list, or export it. The wallet doesn't send transactions on its own and posting the same screenshot again won't help prove that.

**Comment by D3m0nKingx** [comment] 2018-01-06 17:56
Index | Redeemed at input | Amount | To address
-- | -- | -- | --
0 | Not yet redeemed | 381,250.01927000 | DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4
1 | Not yet redeemed | 100,000.00000000 | DKz2xHbRurZbAkUHS21AqrMa295EANmn5C

According to the explorer 100k, was sent to the above address (**DKz2xHbRurZbAkUHS21AqrMa295EANmn5C**). 

The 381,250.01927 was sent to (**DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4**). 

According to this the outputs either went to an address(es) that **you own**, or to **another wallet**.

So the question is what wallet is **DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4** in? Do you have that wallet(.dat), thus having the private key? 

If the answer is no to both those questions, than you're out of luck ....

Another question is...this transaction was on 21st of december, 16 days ago...why are you reporting this now?

**Comment by doge0901** [comment] 2018-01-06 19:46
I do have wallet.dat 
I did not use doge core for a while and than I decided to use some dogecoins to invest in other cryptos, so i had to synchronize it with a blockchain. Unfortunately I did not want to wait so long and sent 6 coints to test whether it would go through, and it did. Consecutively, I transferred the rest , since synchronization was making my computer very slow, unbearable to work with, I only left it to synchronize over night ( some days I forgot to launch it), when it was complete than I noticed this issue an reported.
During my previous research I new it wouldn't matter even I spend coins during synchronization since the balance was bigger than what I wanted to spend. Was I wrong? Thanks

**Comment by D3m0nKingx** [comment] 2018-01-06 20:02
Is the wallet 100% synced now yet? If not, get it synced.

**Comment by doge0901** [comment] 2018-01-06 20:03
Yes, it is I did -reindex once and -rescan 3 times already

**Comment by D3m0nKingx** [comment] 2018-01-06 20:06
Ok well going by your previous post:

```

**Comment by D3m0nKingx** [comment] 2018-01-06 20:16
Ok, going by your previous post:

```
￼validateaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4
11:17:33
￼{
"isvalid" : true,
"address" : "DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4",
"scriptPubKey" : "76a9146d1bd1917c91ea48041d04d2d42ec4e11aac689788ac",
"ismine" : false,
"iswatchonly" : true,
"isscript" : false,
"account" : ""
}
```
>**"ismine" : false,
"iswatchonly" : true,**

Tells me that at some point you **imported** the DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 address to your current wallet, that's what **"iswatchonly : true"** means. In other words you used the command `importaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 "" true` from the console. 

However this address doesn't "belong" to your wallet, it exists from another wallet (hopefully you have access to). The question is can you remember from where you got that address that you decided to use it as a watchonly address?

Also afaik, when you are sending coins, the wallet will **never** use a watchonly address as a "change address" (when you don't specify one). So the only way your coins got sent to that address was by either you specifying that address on the "Custom change address line" in the send window, or actually having specified it as a Pay to: address.

**Comment by D3m0nKingx** [comment] 2018-01-06 20:27
![screenshot from 2018-01-06 15-17-58](https://user-images.githubusercontent.com/18432686/34643627-b1e78690-f2f5-11e7-8615-e8c984a83d9d.png)

Here is where that address could've been specified as the change address, (as you see it would have to be done manually), otherwise it was placed in the "Pay to" field, only other ways the coins could've been sent is using commands in the Console. There's just no other way it could've been sent to that address, other than someone having had access to your wallet.

**Comment by D3m0nKingx** [comment] 2018-01-06 20:34
If you still have your debug.log file you could upload it here and could look there to see. The file is in the same folder as the wallet.dat

**Comment by doge0901** [comment] 2018-01-06 20:51
I did command importaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 from same wallet I used to send coins yesterday, since I thought my computer has been breached and I wanted to watch that address. 
I suspect this address was calculated from my extended address in my wallet.dat and than somehow disappeared. I was extremely cautious no to keep wallet.dat in my computer, before starting client I was synchronizing with different wallet.dat with 0 balance.  And when completed, replaced it with positive balance wallet.dat. Due to my unfortunate cryptsy account with 3 BTC and 1000000doge being lost I was a bit paranoid :). It looks like story keeps repeating...

[debug12-22-17.log](https://github.com/dogecoin/dogecoin/files/1609213/debug12-22-17.log)

**Comment by doge0901** [comment] 2018-01-06 20:55
BTW, I dont even have  "Custom change address line" field in my Dogecoin core when I send coins, only Pay to:   
Label:
Amount:

**Comment by doge0901** [comment] 2018-01-06 21:02
I think I need to do reverse decoding from xprt txid and public key. I just dont know how , my script writing ability is limited.

**Comment by D3m0nKingx** [comment] 2018-01-06 21:21
>I did command importaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 from same wallet I used to send coins yesterday, since I thought my computer has been breached and I wanted to watch that address.

Are you saying you tried `importaddress` for that address which is in the **same** wallet that it is in?? (this would be impossible tho, you would get an error).
Thus, do youhave access to the wallet that has that address? Clearly you know where you got the address from. So again... do you HAVE the wallet where that address was originally created?

>I suspect this address was calculated from my extended address in my wallet.dat and than somehow disappeared.

Which wallet.dat? That's the wallet.dat you need to access that created that address...

Change Addresses:
2. You will see it when you enable it in Settings - > Options... -> Wallet -> "Enable coin control features"

**Comment by D3m0nKingx** [comment] 2018-01-06 21:43
>before starting client I was synchronizing with different wallet.dat with 0 balance. And when completed, replaced it with positive balance wallet.dat

Replaced? so you don't have the old wallet.dat with 0 balance? From the sounds of this that was the wallet.dat that has that address with the coins you sent to.

>I think I need to do reverse decoding from xprt txid and public key. I just dont know how , my script writing ability is limited.

Also you don't have extended pubkey (xpub) (bip32) that you were referring to earlier that's only in HD wallets (example electrum, multibit (bitcoin)). Dogecoin doesn't have any available HD wallets. 

There's no "reverse engineering" a Dogecoin address from a txid, and the public key would be the one you already have. you need it's private key to get access to it's funds either by having the wallet.dat it originated from, or one that it's been imported to...

**Comment by doge0901** [comment] 2018-01-06 22:21
Are you saying you tried importaddress for that address which is in the same wallet that it is in??  Exactly! I sent money from walletA with money to bittrex account, it went through, checked bittrex account. WalletA was backed up. Closed client, deleted walletA, started client, new walletB was created, consequently. Waited to synchronize completely, closed client saved walletB, and pasted walletA, than discovered that it was missing and executed importaddress command. Yes I do have walletB.dat.

**Comment by D3m0nKingx** [comment] 2018-01-06 22:29
Backup wallet.dat (A), replace it with wallet.dat (B) and check if that address is there and the funds...

**Comment by doge0901** [comment] 2018-01-07 02:11
OK, D3m0nKingx I got it.
Half way through. But it is still under watch-only and no in dumpwallet file. How do I make it spendable?
There is a definitely some kind of glitch in a software. 
![dogecoincoreqtwalletb 1-6-18](https://user-images.githubusercontent.com/35134142/34645838-769a7d2c-f31d-11e7-9840-16d894e1da38.JPG)

**Comment by D3m0nKingx** [comment] 2018-01-07 03:03
Firstly, you **cannot** make a watchonly address spendable. Secondly, you need to remember **where** you got the address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 from.  It is an exchange address? (i.e. bittrex?) If you don't have any other wallet.dat files that this address could be residing, I don't know what to tell you. 

bip32 and bip39 have to do with HD wallets. This is off-topic here, and dogecoin doesn't have such wallets. Only two ways you could've created a wallet.dat file with dogecoin core or multidoge wallet. 

So until you can find where that address is from, there isn't anything else I can say :( Wish you best of luck to remember.

**Comment by doge0901** [comment] 2018-01-07 05:30
the sequence or my actions I already mentioned, the question we need to answer how this address got into doge coin QT client that it was used as an output. I did no put this address in change address field manually. Is RAM being used even I close the client? Yes it is very interesting question, how this address got into my computer. Ill try to recover all wallet.dat, if I have any, with data recovery software. The dev team needs to make  the red label not to make any transaction if it is not in sync or even hard code to prevent it. I'll keep it posted. Thanks

**Comment by D3m0nKingx** [comment] 2018-01-07 06:46
I think maybe you just don't remember what you were doing on the 21st of December. 
>I did no put this address in change address field manually.

Even if you did, it wouldn't have worked because, it's not possible to use a "watchonly" address as a change address (When attempting this it would produce an error: "Warning: unknown change address). (I just tested this myself). So you can forget the whole change address argument. 

Therefore, the only possibility left is that you put the address as a Pay to address. 

You're only concern at this point is finding where you got that address from (i.e. another wallet you created, from an exchange, or some other doge service/site/user, etc)

**Comment by doge0901** [comment] 2018-01-07 18:39
I appreciate all the help you guys provide.
I do remember entering only Pay to: DKz2xHbRurZbAkUHS21AqrMa295EANmn5C  amount: 6. I waited until I got it in bittrex account and than 2nd transaction  Pay to: DKz2xHbRurZbAkUHS21AqrMa295EANmn5C  amount: 100000. 
NO way I entered Custom change address, it was impossible since I did not even know about it until you explained me in this discussion. I am 100% sure, no doubt about it. 
You partially are right, I can not possible know exactly what actions I did during synchronization since it took me more than a week to compete it. I was using Bitcoin knots, LTC, multidoge clients  and many more softwares. I am in file recovery mode now and I will try every wallet.dat file I can possibly retrieve to find this address and  private key. Are BTC, LTC wallet private key interchangeable between cores?
Thanks.

**Comment by langerhans** [comment] 2018-01-07 18:58
I already asked this before, but please go to the transactions tab, post a screenshot of it. Also when you click on the transaction on the main screen it will bring you to the right transactions on the transaction tab. Double click them and paste the stuff you see there too. That should give us a hint.

**Comment by doge0901** [comment] 2018-01-07 19:10
![dogecoincoreqt 1-7-18](https://user-images.githubusercontent.com/35134142/34653055-27906716-f3ac-11e7-94e9-00241ebf9c92.JPG)
![dogecoincoreqt-transaction6- 1-7-18](https://user-images.githubusercontent.com/35134142/34653056-27bcdaa8-f3ac-11e7-9cfe-1035478929d3.JPG)
![dogecoincoreqt-transaction100000- 1-7-18](https://user-images.githubusercontent.com/35134142/34653057-27f597da-f3ac-11e7-91fe-83dd6f962591.JPG)

**Comment by D3m0nKingx** [comment] 2018-01-07 19:17
![34653057-27f597da-f3ac-11e7-91fe-83dd6f962591](https://user-images.githubusercontent.com/18432686/34653104-356e84a4-f3b5-11e7-9312-ad3ee87af55e.JPG)
This proves you placed the DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 address into the Pay To field. Change addresses **aren't** displayed in the Transactions detail window.

**Comment by doge0901** [comment] 2018-01-07 20:38
I am sorry but i thought you were trying to explain and help me what happen, not other way around
Unfortunately it proves that input must match output(s) as follows:
{
  "transaction" : {
    "hash" : "6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3",
    "confirmations" : 23048,
    "size" : 225,
    "version" : 1,
    "locktime" : 1992577,
    "block_hash" : "2e8b8343fbe68af6dd7400b620f13199d28310ed7e92426e938adc79590d4eac",
    "time" : 1513912528,
    "inputs_n" : 1,
    "inputs" : [
      {
        "pos" : 0,
        "value" : "481251.01927000",             // this amount must match outputs
        "type" : "pubkeyhash",
        "address" : "DQeNuxSRGCHFLXGZG5nzo1RWBD9RnTW8cP", # **//This is my address with private key**
        "scriptSig" : {
          "hex" : "304402205a737aee03c981adac978eb3e79f91f8b8bd7de036978a14fc85041eeeaa6e2002205a9b48e79932886d3273144a58027b9ea34ab51c79ea48c36b8eb13d0415093401 032c2ec5463cea7385ceab06523ade503a6920949a1d142ca73a343e2f4960340b"
        },
        "previous_output" : {
          "hash" : "07fc72b68d47474cd553439cea70e539b3dd0b1095f3a9df3393c8d32c8a9422",
          "pos" : 0
        }
      }
    ],
    "inputs_value" : "481251.01927000", 
    "outputs_n" : 2,
    "outputs" : [
      {
        "pos" : 0,
        "value" : "381250.01927000",
        "type" : "pubkeyhash",
        "address" : "DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4"     // change address, where the hell it got from, nobody knows, you need or dev team at least to figure out what are possibilities  it got here due to my computer virus, glitch, memory misplacement, other core clients running simultaneously and using wallet files without me entering it ,that is deep subject to begin, without coming from dogecoin wallet.dat private key pool. I DO REMEMBER entering ONLY one Pay to address which is output 1 below
      },
      {
        "pos" : 1,
        "value" : "100000.00000000",
        "type" : "pubkeyhash",
        "address" : "DKz2xHbRurZbAkUHS21AqrMa295EANmn5C"
      }
    ],
    "outputs_value" : "481250.01927000",
    "fee" : "1.00000000"
  },
  "success" : 1
}

**Comment by D3m0nKingx** [comment] 2018-01-07 20:56
>"value" : "381250.01927000",
"type" : "pubkeyhash",
"address" : "DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4" // change address, where the hell it got from, nobody knows, you need or dev team at least to figure out what are possibilities it got here due to my computer virus, glitch, memory misplacement, other core clients running simultaneously and using wallet files without me entering it ,that is deep subject to begin, without coming from dogecoin wallet.dat private key pool. I DO REMEMBER entering ONLY one Pay to address which is output 1 below
},

this is **NOT** a change address. this is a WATCHONLY address that you ADDED to your wallet. now you're saying "where the hell it got from" when you're the one that said yourself you IMPORTED it to your wallet (https://github.com/dogecoin/dogecoin/issues/1419#issuecomment-355775613), are you aware of your own words here?

Either way I already told you what you need to do: 1) having the wallet.dat, 2) the address' private key or 3) some other place it is from (an exchange, another user, or some other site). 

Other than that I'm sorry to tell you but if you can't find it from one of these 3 things, you're out of luck.  buddy. 

So until you produce something that satisfies one of the 3 conditions I listed. There's nothing more to be done or said here.

**Comment by doge0901** [comment] 2018-01-08 00:44
I added this address to my wallet on 1/5/18 to watch it from my wallet since I did not have private key due to my suspicion than my computer been hacked and coins stolen. I mention that already.
The transaction with this address executed on 12/21/11. My grounds are totally correct.
1. I commit transaction with 6 and 100000  ONLY FIELD "pay to" used: DKz2xHbRurZbAkUHS21AqrMa295EANmn5C
2. After synchronization complete I notice more  coins are missing than what I sent
3. Go to https://dogechain.info/tx/6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3
to find where my coins been sent to.
4. Find that output 0 being used as address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4, I do not have private key for it.
5. Enter importaddress DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 into client console as watch only( no private key).
All there actions executed in the same wallet.dat, except synchronization.
If do not not believe me it is fine. Whats the point repeating myself. That is the reason I've started to look for answers.
The answers still remain ...Where these address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 and DM8aSq4RYPL2ZdKMbxNGuYydvLCY944uUN  came from  if I did not put them manually?

**Comment by jokeranon** [comment] 2018-02-04 18:31
Hi, doge0901 
I have solution to your not redeemed yet problem, text me on telegram: darkstar_anonymous

**Comment by mmoren73** [comment] 2018-09-14 20:36
omg you guy are no help, ive got the same damn problem, my wallet just FOR NO DAMN REASON SENDs OUT 13K IN DOGE, AND THEN AGAIN YESTERDAY ANOTHER 2k, explain that einstein,  my wallet is updated and encrypted, but yet two transaction to some address i have no idea belongs to gets sent out. if my wallet is encrypted then no should be able to send, but yet they did. and my keys are written down in a notebook, no passwords are saved on my pc, ever! so tell me where are my coins going?

**Comment by mmoren73** [comment] 2018-09-14 20:41
exactly doge0901 where are these address coming from, i have two i have no idea where they came from, i followed one transaction back to a wallet with 7 million doge in it, what to hell is going on, the devs scamming coin or something? has the wallet been compromised and the devs dont want to admit it? ididnt have much doge int he first palcebut it took me a while to build those up and this is BS, im pretty sure i wasnt hacked, my wallet was encrpted with a safe key written on paper in a notebook, what the hell is goin on, im not uising a wallet that just spits out my coins to anyone randomly

**Comment by leuqarte** [comment] 2018-09-14 23:02
@mmoren73 can you provide more information (links to logs, transaction records, etc. like doge0901 did) - BTW yelling, name-calling, and accusations aren't very helpful for either you or the devs; keep that in mind...

**Comment by Fulvio55** [comment] 2018-09-15 00:38
First step is to verify that you have a copy of the keys for every wallet in there, and stop using the client.

Perhaps use coinb.in to move all the coins to a new wallet generated using walletgenerator, with the keys only recorded in a text file or on paper and not accessible to the client at all. Read the many posts on /r/dogecoin about doing that.

QT has been in use for nearly five years by hundreds of thousands if people without incidents like you mention. Throwing wild accusations around is not justified or warranted.

I'd be looking to your personal arrangements being compromised. Whether malware or someone with physical access, that is far more likely than bad code in the client.

So yeah, quarantine your coins first, investigate your own environment , and provide much much more detail rather than accusations.

**Comment by mmoren73** [comment] 2018-09-15 01:05
your like one of these small town doctors that thinks every cough is just
the flu, and cant possibly be anything but. well i know my pc is secure,
100% i know pcs, much more then i let on, i have 35 yrs in the field, so
maybe you shouldnt be so quick to think everyone is an idiiot around you.
my pc i s100% secure, wallet encrypted, paraphrase is written in a notebook
and i live alone. so with those facts in the mix, its more then likely one
of your pal Devs suck at coding, or hes skimming off the top, i followed
the money trail to a wallet with over 7 million doge in it, and there were
tons of other transactions being sent to this one wallet. and those keys i
have no ideas whos they are, they have nothing to do with my wallet or any
watch keys or any bs like that. im pretty sure some one beat the encrpytion
by bypassing it, there is no way he can get my private key, like i said i
write all passwords down in a notebook, i wasnt born yesterday, n i dont
use a cam.

**Comment by Computer-Genuis** [comment] 2018-09-15 01:45
What you don't seem to understand is that no one can just access a wallet without the private key. 

So if you think someone "skimmed" your wallet, your private keys were most likely compromised in some way.


> So yeah, quarantine your coins first, investigate your own environment , and provide much much more detail rather than accusations.

If you "know pcs, much more then i let on,", you should know that problems can only be solved if all the infomation you have is given to the people trying to help you with your problem. 

What is your encryption? By that, I mean do you have a password on your wallet, and how long is it?

**Comment by Fulvio55** [comment] 2018-09-15 02:12
Sorry, I'm not interested in abuse. Not on Reddit, and certainly not here.

You need to calm down and change your tone.

**Comment by D3m0nKingx** [comment] 2018-09-15 03:34
https://github.com/dogecoin/dogecoin/issues/1419#issuecomment-355866914
@doge0901 you never mentioned DM8aSq4RYPL2ZdKMbxNGuYydvLCY944uUN prior to the above posting, only addresses:  

DKz2xHbRurZbAkUHS21AqrMa295EANmn5C and DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4

**Comment by langerhans** [comment] 2018-09-15 07:54
@mmoren73 if you have so much experience in the field then you should be able to check the code and see that the wallet doesn't magically send coins anywhere without being told so.

Anyway given no useful discussion is happening here anymore I'll close the issue. Feel free to open a new one when you calmed down and stopped throwing a hissy fit.

**Closed** 2018-09-15 07:54 UTC

**Comment by tcon44** [comment] 2021-02-01 22:01
> Hi,
> please help me to redeem the coins back.
> I have windows 10 (64bit) with Dogecoin Core QT 1.10 wallet
> After I made 2 transactions ( wallet was not entirely completed to sync ) 6 and 100000, wallet made other 2 transactions for no reason https://dogechain.info/address/DQeNuxSRGCHFLXGZG5nzo1RWBD9RnTW8cP
> transaction https://dogechain.info/tx/6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3
> Amount I sent only 100000 6f11ae8637c6b4232aee40e0a0f31d605c54c393ab53007fa744a97f8e2747b3-001
> How I got other amount-381,251.01927000 sent ?
> Please help me to retrieve it.
> Thank you
> 
> PS: I Synchronized it completely and than re-index it with no luck to show balance correct.
> I did not do anything with wallet.dat except encrypted it with new passphrase since I restored it from unencrypted usb flash which I kept it as a back up.
> It is synchronized fully
> I do no have such address DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4 after I did dumpwallet and printed to find it.
> This is really weird. Any other suggestions to reedem it?
> Thank you.

Hey the same thing happened to me with Dogecoin.  I had 324,000 coins sent to a random address.  I have my Dogecoin back up dat I am trying to access that now.

**Comment by doge0901** [comment] 2021-04-19 02:10
I think I understand what happen.
Every time I made transaction wallet.dat somehow created new change and reserve addresses. As I copied my wallet.dat over from USB drive to core data location, made transaction and I did not make a copy after the transaction was completed. Eventually, wallet.dat got overwritten or deleted. I can not remember... But it seems than i need to restore all the old wallet.dat files, if possible. My guess I'll contact professional hard drive restoration company to try to get it back or just sell a hard drive if someone wants to buy.
Here is a lot of info to understand what happens in wallet.dat https://developer.bitcoin.org/devguide/wallets.html#loose-key-wallets
BTC is same or similar as Doge 

Thank you for your help

**Comment by wallet0dat** [comment] 2021-05-08 22:09
hello dear @doge0901
send me a email I can help you about that if you not fixed it yet
coreusertest [at] gmail [dot] com
king regards

**Comment by Senna22** [comment] 2021-11-29 06:40
@wallet0dat can you help me?

**Comment by wallet0dat** [comment] 2021-12-09 03:43
> @wallet0dat can you help me?

https://t.me/freshtools
coreusertest@gmail.com

**Comment by dismas44** [comment] 2024-11-20 16:22
> I think I understand what happen. Every time I made transaction wallet.dat somehow created new change and reserve addresses. As I copied my wallet.dat over from USB drive to core data location, made transaction and I did not make a copy after the transaction was completed. Eventually, wallet.dat got overwritten or deleted. I can not remember... But it seems than i need to restore all the old wallet.dat files, if possible. My guess I'll contact professional hard drive restoration company to try to get it back or just sell a hard drive if someone wants to buy. Here is a lot of info to understand what happens in wallet.dat https://developer.bitcoin.org/devguide/wallets.html#loose-key-wallets BTC is same or similar as Doge
> 
> Thank you for your help

**Comment by dismas44** [comment] 2024-11-20 18:15
@Doge0901 you must have figured this out.
Because the wallet address (DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4) that the coins were sent to have been sent Aug 2021.  
 
![DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4](https://github.com/user-attachments/assets/d182b695-be64-4726-b3e3-aba3befeb6d1)

Also see here below live

https://dogechain.info/address/DF61X3Gn1H8zVeV2QoERgprKAivufsVkA4

The issue is neither of us entered these addresses into our wallets prior to the wallet sending the coins on it's own.  The good news is it seems to be fixed via the results above as @doge0901 successfully got access somehow to his misplaced coins.  But i do not see any posting after that nor do I know how to get in touch with @doge0901 because you cannot direct message here I've read.   if anyone could help I would greatly appreciate it.  I am not as technically skilled as @doge0901 and with $100K now on the line i don't want to screw it up.

My main question at this point is this.  Since two of my computers that held the wallet are down right now, is it possible to recover with just a new install of the wallet and the old wallet.dat file?   Or is it a combination of the old wallet on the old computer and maybe even some hard drive entries and the wallet.dat to successfully recover?

**Comment by dismas44** [comment] 2024-12-08 23:58
I was able to get into my wallet and i see that the coins were sent but I dont  know what to do next.
