### ISSUE TITLE
I was scammed and I need help . I can see that my transaction iD and wallet address of recipient and it says not yet redeemed .

### ISSUE THREAD

**Issue by klawdarza** [dogecoin/dogecoin#1938] opened 2021-05-15 13:30 UTC
I was scammed and I need help . I can see that my transaction iD and wallet address of recipient and it says not yet redeemed . 

I sent my dogecoins to

D6Sb98cbaDyQpYbHCMQmpaLxZe6LctqAj3

Because I was stupid to believe they would double it .
![image](https://user-images.githubusercontent.com/68105594/118347544-c1601500-b576-11eb-9264-8c14e98fc1cd.png)

The website was dogecoin-snl.com and I learned about this giveaway from YouTube . Why do they air scammers ? ![image](https://user-images.githubusercontent.com/68105594/118347555-d472e500-b576-11eb-85ce-25fed2b58d81.png)

__Originally posted by @klawdarza in https://github.com/dogecoin/dogecoin/issues/1880#issuecomment-841596661__

**Comment by blacklightpy** [comment] 2021-05-16 04:33
Your coins are gone.

**Comment by klawdarza** [comment] 2021-05-16 04:47
Thank you for confirming .. I didn't know who to ask if it was finally gone.thank you . It hurts.

**Comment by gewure** [comment] 2021-05-17 00:32
This is the Dogecoin repository. Im sorry for your coins, but this has nothing to do here honestly.

**Comment by kitcateleven** [comment] 2021-05-17 01:38
If my backed up HD helps, LMK - I am not a coder, just a node.  if you need me DogDevs, lmk

**Comment by klawdarza** [comment] 2021-05-17 07:49
Hi Kit , is your comment for me ? I don't know what backed up HD means .. but if you want to help me .. of course .. 

I do know that if someone would check the address in the chain they will realize there is a bigger issue than me losing coins . The amount I sent is not the amount received by the wallet .. there is a bug . 

Thank you thank you so much

**Comment by caseyPav** [comment] 2021-05-17 09:15
No offense - there is not a bug. You clicked a link that was like iirc
dogecoin-snl.com. And then sent obvious scammers your doge.

I'm sorry for your loss.

Your coins are gone.

The blockchain is immutable.

Devs have no control over it & can do nothing to revert transactions.

If you wish to track down the scammer. Take it to reddit or discord.

This *is not the correct forum for your issue*.

Please close this issuebqnd take it to reddit or discord where it belongs.
No one can do anything for you here. You sent coins to someone who promised
to double them. You did not get them back.

This also happens to new players in RuneScape with gold.

Please, close this issue and take it to the community.

This has nothing to do with the dogecoin codebase.

I'm sorry for your loss.

The blockchain is immutable.

Please. Stop.

**Comment by blacklightpy** [comment] 2021-05-17 09:41
> Hi Kit , is your comment for me ? I don't know what backed up HD means .. but if you want to help me .. of course ..
> 
> I do know that if someone would check the address in the chain they will realize there is a bigger issue than me losing coins . The amount I sent is not the amount received by the wallet .. there is a bug .
> 
> Thank you thank you so much

I checked the transaction. Since you sent your amount from Binance hot wallet, there were some others too who sent to the same address. Binance bundled all those transactions and sent it in one input.
Here's the transaction ID (from your screenshot): https://dogechain.info/tx/fc27ef7705e1331634ff324a7b88d94794271c7d645699f11ed98089481ee58b
It's showing not yet redeemed, but I think that's because their client hasn't synced. But it's got 11k+ confirms so the transaction is already processed.

Learn about crypto first. Don't send from an exchange wallet for an external transaction - it makes it hard to track, and also you won't get any refunds because the address is the exchange's hot wallet - not your deposit address.

**Comment by klawdarza** [comment] 2021-05-17 10:18
No offense too but after  much thought, 



I didn't send my coins because I didn't  have a wallet . I bought dogecoins from Binance and Binance sent them . 

I don't know if Binance uses a  wallet  to do that or not . 

Second,I was instructed to send my coins from a Doge wallet and not from a platform .. and they specifically mentioned that if I sent through Binance or Robinhood etc , it was more complicated because I would have to connect my Doge wallet to Binance and send them that wallet address ..

I didn't send my trust wallet nor connect  it to Binance. 

I was directed  to a site called Wallet Verifier and it integrates all kinds of Doge wallets including Dogewallet . ![image](https://user-images.githubusercontent.com/68105594/118465457-7c81dd00-b734-11eb-8d1f-7d543c463cd6.png) 

 Please bare with me because this issue is more than just a bunch of coins lost .

Ultimately , it has to do with  Dogecoin having no  ![image](https://user-images.githubusercontent.com/68105594/118467447-5fe6a480-b736-11eb-84cb-7a6743f27767.jpeg)
![image](https://user-images.githubusercontent.com/68105594/118467566-77be2880-b736-11eb-913f-11d3472b3223.jpeg)


It is a bug . The transaction was only for 8,043.4. Dogecoins .

Why is the amount on the address 20,000 dogecoins 

It also remains unredeemed .

In dogechain, the wallet ha 1.6 mil dollars , in unmineable , it has 0 , in blockchair, the address is not valid .

Is this not an issue that must be resolved ? 

The issues above can be referenced in a few other posts ... Specifically phantom wallet addresses, and the blocks that can't be closed .. 

Dogechain if it is indeed true that it is for the common people cannot justify to the Fed or the ignorant , sorry you have no recourse . 

No .. that's not acceptable. That's not going to be acceptable because we don't have the ethical backbone .

We don't want a currency wherein we need to do research if the recipient is not a scammer or one whose wallet has been used numerous times for scamming . The Doge blockchain has numerous issues which need to be solved . 

Also , Don't we have to declare every earning and expense and loss  to IRS ? 
Sorry but I am tired of being told that this is not the right forum .
 
I realized now that decentralized means no one gives a hoot about me or those who were scammed . 

No one is accountable and no one to help .

In fact ,I tried telling my mom to report this to Reddit and she gave up because the Doge developer wants karma before she can comment or she has to invite people to be in discord  . What is that? 

I am not into video games and we want simple forum to air our concerns . 

It's ok..you can take this down if you like and there is no forum I can post it on anyway .. 
 I feel like decentralized means defunding the police .

To each his own . 

No that's not possible . Some of us are so tired with physical labor that we can't even lift our arm much less research if the currency of the future tells me I have to research and study .. 

Thank you . I represent half of the population . Of the world . The ignorant don't deserve to be scammed . 

![Uploading 

118472789...]

**Comment by klawdarza** [comment] 2021-05-17 10:29
Hi @blacklightpy maybe I am a magnet for scammers but I was tweeting  today and I get a notification that says I am added to a list  and it's the address of the scammer. ![image](https://user-images.githubusercontent.com/68105594/118474329-878d3b00-b73d-11eb-9052-83d84e183fae.png)

How can he be stopped ? 
If you go to Twitter  , the scammer uses Binance as name  and has a link .

Thank you ![image](https://user-images.githubusercontent.com/68105594/118474593-d044f400-b73d-11eb-9d6b-f58a47fbaf36.jpeg)

**Comment by klawdarza** [comment] 2021-05-17 11:02
What is repository ?

**Comment by Raunchard** [comment] 2021-05-17 13:49
stop wasting the devs time with this.

**Comment by gewure** [comment] 2021-05-17 14:05
@klawdarza Hello?
THIS IS NOT THE PLACE FOR THIS!

This is about developing doge core source code - Please, go somewhere else! Github Issues are no-way meant to resemble such a forum.

If this only was better moderated...... :(

**Comment by zBl4ckUser** [comment] 2021-05-18 00:28
I'm sorry for your coins, but this is not the place for this.

**Comment by mishushakov** [comment] 2021-05-18 01:27
guys, please at least have some empathy for this person and forgive her for her lack of insight

@klawdarza i'd advise you to leave everything as is

and stop assuming us to be at fault for your actions, we're not your guardians
bye

**Comment by blacklightpy** [comment] 2021-05-18 15:12
> I don't know if Binance uses a wallet to do that or not .

All coins belong to a wallet. In centralized exchanges you just trade under their custody so you are not given their keys.

> It is a bug . The transaction was only for 8,043.4. Dogecoins .
> Why is the amount on the address 20,000 dogecoins

It's not a bug. You used a centralized exchange instead of your own wallet. They always bundle transactions while sending. It's not Dogecoin's fault. It just means that at the moment you sent, some others too sent coins, and Binance couple them. It's an exchange, so you're not expected to make direct purchases from there, also considering it's irrational because of the high fees.

> In dogechain, the wallet ha 1.6 mil dollars , in unmineable , it has 0 , in blockchair, the address is not valid .

In Dogechain and Blockchair, the address D6Sb98cbaDyQpYbHCMQmpaLxZe6LctqAj3 (scammer) currently has 3,078,049 DOGE and DST6SbB33rukG7mYCgc3qus4jY2DzH3PHR (temporary exchange wallet) had 82,022,266.62497368 DOGE initially and 0 DOGE now, after the transaction. Unminable isn't a blockchain explorer - it's a mining platform, and it only shows their balance towards your address.

> Is this not an issue that must be resolved ?

No

> Specifically phantom wallet addresses

I told you it's a mistake. Even then, you can send coins to an unusable address to burn the coins. So the existence of Phantom wallets is not a bug either even though that's not what happened in your case.

> and the blocks that can't be closed ..

???

> Dogechain if it is indeed true that it is for the common people cannot justify to the Fed or the ignorant , sorry you have no recourse .

Your feelings are irrelevant. Yet I doubt even the banks would help you in this case. You can justify this to the feds and there's nothing stopping you from that, although I doubt if they'll help. This was a stupid mistake, own up to it.

> No .. that's not acceptable. That's not going to be acceptable because we don't have the ethical backbone .
> 
> We don't want a currency wherein we need to do research if the recipient is not a scammer or one whose wallet has been used numerous times for scamming .

You lost your coins because of your greed. Dogecoin will not implement KYC. Cryptocurrencies fundamentally provide you financial freedom, but you are responsible for your choices.

> Don't we have to declare every earning and expense and loss to IRS ?

You can report that you got scammed, and count it as loss.

> I realized now that decentralized means no one gives a hoot about me or those who were scammed .

Exactly. But not exactly. Decentralized means you are given financial security at the condition of responsibility. Banks have the same thing. If a bank makes a mistake, they can't get help because they were supposed to be responsible. Cryptocurrencies just makes gives you the capability to be your own bank.

> No one is accountable and no one to help .

You were accountable for your actions. And yeah, there's no one to help - because that's how a system works. You can't yell at a knife because you can't play football with it, because that's not what it's designed for. Cryptocurrencies give you the ability to verify whatever's going on under the hood because it works under open source code, so you don't have to trust anyone and just verify the code independently. If that doesn't suit you, maybe cryptocurrencies are not for you - although it's better for you. Maybe give the responsibility of handling your coins to someone else. The world doesn't revolve around you and you should know how how to have financial security.

> The ignorant don't deserve to be scammed

Cryptocurrency itself is a protocol and it doesn't get you scammed in it's own way. You walked right into the hands of a scammer and that's why you lost your coins.

The fundamental idea of Bitcoin is that if you have your private keys, no one can take custody of your funds without your consent. That also means that if you make a mistake, no one can take funds back from the scammer too.

The best you can do is to file a case againat the scammer and hope he gets caught. But anyways I think you'll atill have a hard time getting your coins because you sent it from the exchange wallet and also you have no idea how cryptocurrencies work.

> Hi @blacklightpy maybe I am a magnet for scammers but I was tweeting today and I get a notification that says I am added to a list and it's the address of the scammer.
> 
> How can he be stopped ?

Keeping your online identity clean of scammers is a personal responsibility. Twitter is filled with spammers and it's possible that you got targeted. Maybe try cleaning up your online information, and if not, make a new Twitter account. This is unrelated to Dogecoin.

Please understand that this is not your common sense advice platform. Any such discussions should go on Reddit. This is where we discuss technical limitations and updates to the codebase. Your case is not a technical error, rather a personal mistake.

To finish with some quotes to hopefully make you understand,

**_"Until you take responsibility for your actions, someone else runs your life"_** ~Orrin Woodward

**_"Liberty means responsibility. That's why most men dread it."_** ~George Bernard Shaw

**Closed** 2021-05-20 09:59 UTC
