### ISSUE TITLE
why DNS has great effect for the speed of sync dogecoin core-wallet data?

### ISSUE THREAD

**Issue by quark2019** [dogecoin/dogecoin#1861] opened 2021-04-29 03:39 UTC
When the delay of ping DNS  is about 250ms,  the speed of sync with dogecoin core-wallet data is about  500Mb per 24 hours;

when the delay of ping DNS  is about 3ms (just by change DNS server to a local one),  the speed of sync with dogecoin core-wallet data is about 3Gb per 24 hours;

So the questions are:
-- Why DNS has great effect for the speed of sync dogecoin core-wallet data?
-- How to cache dogecoin seeds to avoid query DNS again and again?

I would hope these answers will help other people when trying to sync the dogecoin data.

---------------------
BTW, I'm using a 1Gb optical fiber network in a center city, however, it still very very slow to sync dogecoin core-wallet data.
Dogeoin core-wallet data is near 600Gb?  it may take about 200 days to finish the sync ...

Any way to speed up the sync?  

Much thanks!

**Comment by ReverseControl** [comment] 2021-09-02 21:36
@quark2019 Could you please test again and report your results?

**Comment by patricklodder** [comment] 2024-01-07 15:15
The cause of this is not the DNS server but the peers you connect to when doing sync. 

- 1.14.0-1.14.2 had a bug in supplying blocks, which was fixed with #1676 in 1.14.3. Any peers of 1.14.3 or higher will supply blocks much faster than prior versions.
- 1.14.0-1.14.3 had a bug in requesting headers, which was fixed with #2417 in 1.14.4. Please use this version or higher to make sure your client efficiently requests headers.

**Closed by patricklodder** 2024-01-07 15:15 UTC
Labels: question
