### ISSUE TITLE
Peer-to-Peer Dogecoin Relay Network (based on Starlink)

### ISSUE THREAD

**Issue by arthurgervais** [dogecoin/dogecoin#2124] opened 2021-05-25 20:07 UTC
There exist several technical bottlenecks to scale Proof-of-Work (PoW) blockchains. Some of them are the CPU time for transaction validation, the hard disk space to store the chain, and many others.

One of the most often overlooked bottlenecks is the communication latency and Internet speed between miners. The slower the Internet between the miners is, the less synchronized they become, and the more the blockchain security degrades. That is one of the fundamental reasons why it’s not trivial to scale Doge- or Bitcoin [by simply increasing](https://eprint.iacr.org/2016/555.pdf) the block-time frequency and the block size. You can find empirical results for blockchain network simulations [here](http://arthurgervais.github.io/Bitcoin-Simulator/results.html).

**Dogecoin on Starlink?**

Now, one way to speed up a blockchain without any protocol change is to simply improve the network connectivity between the miners! This is where Starlink, the satellite-based Internet from SpaceX could help Dogecoin to be closer to the moon.

Starlink latency between London and Singapore is expected to be much lower than current Internet round trip times (RTT). Starlink could hence speed up Dogecoin’s block and transaction propagation, effectively scaling its blockchain substantially.

![1_xjFd6c4GylHPlSh9s9VO2Q](https://user-images.githubusercontent.com/8501292/119561425-6e236900-bda5-11eb-8390-eae7c30a624a.png)

Mark Handley [beautifully simulated](https://youtu.be/QEIUdMiColU?t=288) how much lower the latency of Starlink would be, when compared to the current terrestrial Internet. For example, he estimates that the round trip time (RTT) between London and Singapore would be about 108ms on Starlink, while Fiber optic Internet currently yields 159ms.

Starlink is certainly already highly anticipated by traditional financial institutions to perform lower latency arbitrage across the major financial exchanges. Using Starlink as a network to propagate blockchain peer-to-peer data among miners would equally help speed up substantially the current blockchain throughput, without deteriorating its security. Naturally, a possible risk here would be for a single for-profit company to effectively own the entire blockchain relay network, a risk that may be mitigated with future orthogonal satellite Internet services.

**Blockchain Relay Network**

Analogous to the [FIBRE network](https://bitcoinfibre.org/), [Erlay](https://arxiv.org/abs/1905.10518), and other prior relay networks, Dogecoin could very well scale its transaction throughput by orders of magnitude, if its miners were to engage in a dedicated Starlink relay network. Naturally, this relay network propagation protocol should be optimized for the Starlink characteristics to fully take advantage of its topology.

Quantifying the optimal protocol, and parameters is certainly a very exciting avenue towards scaling Dogecoin! What do you think?

**Comment by patricklodder** [comment] 2021-05-25 20:17
I'd totally run some relay nodes on satellites instead of my current terrestrial ones... that would be awesome. Would this need to run something different than TCP though?

**Comment by Reclad** [comment] 2021-05-25 20:49
I think you just found something very important. I propose here an additional idea (probably silly but I am learning).
I prefer to prevent, I just try to imagine what will be done with Dogecoin in the distant future.

I always thought that Starlink (Elon) was intended in the distant future to reduce the latency between the earth, the moon and Mars. Obviously we will have communication protocols which will probably be adapted to the high latency and there will necessarily be methods of synchronization between the nodes of each planet. If I transpose your idea on what mechanics it will be necessary to adopt for a multiplanetary crypto, it will be necessary that the miners go through the lowest latency and Starlink seems to be built to obtain this reduced latency (because currently it is indeed the Starlink satellites which would be closest for network communication to the Moon).

Questions :
- Is it possible to have a multi-planet blockchain? If there is extreme latency between a miner from one planet and the other. Can the PoW method (_or how you describe it with Blockchain Relay Network_) work  ?
- Can we work on this PoW method to adapt it to extreme latencies? (For example "master" nodes would exist between each planet and would be authoritative to validate a blockchain (not a transaction) -> I know it's probably idiot)
- Shouldn't we just work on a particular proof of work for operation with extremely slow latencies? At least, allow certain specific nodes to have extreme latencies.

Of course, there is no point today in having a crypto-miner on Mars, it is a question here of imagining the Dogecoin in the distant future and trying to anticipate what will come.

**Comment by arthurgervais** [comment] 2021-05-25 21:31
Great question @patricklodder, afaik, Starlink is currently aimed at IP, but I hadn't yet the chance to get my hands on one to test around what could be done. Instead of TCP, the Starlink relay network could be using the quicker UDP or other variants with error correction codes, but as you also imply, I suspect that a dedicated protocol may perform better. I would love to do further research in this direction to help scale Dogecoin on layer 1.

Equally intriguing questions @Reclad. Let me try to get to them one by one:
1) re multi-planet blockchain: just like between nodes on earth, we would want the latencies between nodes on different planets to be minimized, while the bandwidth should be maximized.
2) re master nodes: the introduction of master nodes may be possible, but this is likely to come at the expense of centralization, and reduced fault tolerance.
3) re extremely low latencies: low latencies are exactly Starlink's goal, and worldwide low latencies are what Dogecoin needs to scale by orders of magnitudes.

**Comment by patricklodder** [comment] 2021-05-25 22:23
So then this just becomes a matter of deploying existing software on a couple of satellites. I think what you'll want to do is pitch this to people that run satellite networks. I can think of a high profile person on twitter? :-)

**Comment by Reclad** [comment] 2021-05-25 22:25
Ok, sorry for that. I think I don't explain myself well.

So I made a tiny diagram, just to illustrate what I think and what dogecoin dev should anticipate if Elon Musk choose this crypto. 
![relaynetwork](https://user-images.githubusercontent.com/350119/119576098-66b98b00-bdb8-11eb-8da6-fd6165febcf4.jpg)
I'm pretty sure that Elon Musk choose "Starlink" name for a good reason and he try to find out crypto which can be linked between planet. For now, P2P and Proof of Work seems not adapted for multi-planet interaction. But Relay network perhaps, and this can be boosted if the dogecoin network goes through Starlink as soon as possible. 
(My apologies if I misunderstand some concepts, these are just ideas.)

I won't bother you anymore, I'm probably off topic. :)

**Comment by godcloutier** [comment] 2021-05-26 00:11
from elon's tweet not so long ago I saw that ARK did something as a "testbed" for bitcoin to use starlink. Maybe thats something we could look into. The work seems to be advanced from what I understood. Will need to find the link again.

**Comment by soraimperial** [comment] 2021-05-26 01:15
@godcloutier Couldn't find what you mentioned, except this ARK TX that was sent through Starlink, if the original sender's tweet is to be believed.
https://explorer.ark.io/transaction/b1fbc0888267dade978360cbbd09c0b462c128b5f0823dec1df63e7936e406b9

I did find on their github, however:
https://github.com/ARKInvest/SolarBatteryBitcoin
A solar power system that has a mining rig attached to it to up $ profitability. Although focused on returns to grid, made me think of the profitability of a mining farm on Mars (even if solar power is 44% weaker than on earth). But I digress.

**Comment by ThisIsMyDogeAccount** [comment] 2021-05-26 02:06
> l I can think of a high profile person on twitter? :-)

I have created a tweet and have tagged Elon.

Not trying to say I'm doing the most work in this thread, but I'm going to have to take a break now. 😅

Honestly though I love the conversation going in here

**Comment by Im-Mr-Chris** [comment] 2021-05-26 03:01
But is starlink "decentralized"? Otherwise, why build on it?
Apologies if this off topic but it needs the foundation of complete decentralization.
In the end if it wasn't, I don't see this as any different than the paper version.

**Comment by soraimperial** [comment] 2021-05-26 03:11
Venturing on the offtopic a bit more:

I'd argue it's just a way of distributing information, aka, building a relay network.
For it to be centralised in the whole context of a blockchain, Starlink would need to hold a certain % of actual nodes in the satellites. Otherwise, I do not see using Starlink as a network relay as any different as the regular ISPs that relay information for earthly nodes.
I see it like the evolution of ADSL to fiber, highly reducing latency with our current technology, except it can also potentially allow for interplanetary blockchain ventures.
I think it could be considered centralised if anyone ever sets up Doge nodes on the moon/mars and they become entirely dependent on a Starlink relay, where they'd be at the mercy of one single entity. But there are several patents for satellite communication constellations (I think Google was the first?), Starlink might not be the only one on the race to outer space internet.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 03:27
THANK YOU! I felt like I was the only one thinking from more than one place.  Probably why I felt so out of place tbh. 

Rhetorical question....
If BTC = Digital Gold
and 
if ETH = OS to install dapps

Then ICP = The Internet Computer (Protocol).

The source code is on dfinity's github.  Anyone using nearly any language can start building right now through motoko. We can build on this! 

Additional Tangent while I have your attention:

 We can use $DOGE currency convertible as Tokens and cycles, 
 
 "Cycles are required to power canister operations for applications running on the Internet Computer".
 
 All devs, engineers, entrepreneurs, etc. can have a REAL reason to buy doge and leave the current internet.  Wouldn't this solve the whole POW and POS at the same time?
 
I'm mentioning this before ANYONE in every single thread from what I've discovered.  Most crypto investors dont fully understand the concept of btc, etc, and doge.  wait until they finally zoom out and see what utility really means.  THIS will put doge on the map and really detach this whole "meme" nonsense aside based on the correct approach.  

Who would imagine....Doge became more decentralized than ETH and ADA?
AND, gave the entire content creators, dreamers, ANYONE a reason to not just buy doge, but to BELIEVE in DOGE!

Okay....I'll stay quiet now. I've done what I could as a citizen of the earth and a member of this community.

**Comment by bernTOAST** [comment] 2021-05-26 03:29
It's like saying web hosting a site isn't decentralizatized or using Internet providers isn't decentralizatized. Also why does it matter. One dev has 15 nodes of his own... What's starlink to have a few hundred of their own nodes. At least until we have own relays paid by doge funding.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 03:37
Now that you mention that, I'm curious...

is starlink even open source to begin with?

starlink is hardware. imagine icp running on literal hardware in outer space?!
sht....idk anything about the architecture, but if motoko is advanced and compatible as it currently is (finger print scanner on mac, face unlock is directly implemented WITH this blockchain technology! You can't beat that guys!

**Comment by usayao** [comment] 2021-05-26 04:06
so cool

**Comment by tzarebczan** [comment] 2021-05-26 04:13
Can't wait for the implemention, we'll get it added to LBRY once it's good and tested!

**Comment by thetigerking** [comment] 2021-05-26 04:16
Can we add Tesla to this mesh topology?  I envision (as I'm sure Elon already has, since he did tweet, "dojo 4 doge") that each individual vehicle, home solar installation, and the supercomputer (dojo) will allocate some resources to processing DOGE transactions.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 04:33
When you say Tesla, my imagination goes directly to starlink, nodes, then canisters, built upon SUb nodes.
The entire concept of crypto is to be decentralized right? 
This also needs to apply to the access of information at any given time, place, without restriction, at an operational cost.  
My phone got cut off today IRL because.....well I bought the dip. 
ANYWAY, 
I felt so detached. I was literally scared because I didn't know what was going on.  (I didn't have access the the public wifi).
Anybody in lets say AFRICA, can use any device connected to starlink.  This takes us off centralized and aws internet right now. 
Please, somebody have some belief in me because im at the verge of tears here. we have to make dogecoin work someway, somehow. my inner peace depends on this.

**Comment by delbonis** [comment] 2021-05-26 04:37
@Im-Mr-Chris 

>Please, somebody have some belief in me because im at the verge of tears here. we have to make dogecoin work someway, somehow. my inner peace depends on this.

On the contrary, if your mental health is dependent on the success of an open source project then you might want to consider pulling out and taking some time off.  Your mental health is important and being over invested will lead to thoughts of guilt and regret if it doesn't go well.  Consider talking to a professional.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 04:44
I've been through the "professionals". I've been "medicated".

My mind just works this way and its why I understand Elon.  I don't care if I lose it all, I'm here, what else is there to do?! Watch netflix and go out and do whatever regular people do?! 

I've been put through the ground, embarassed, bulied, all that.  I gave up years ago on my dreams.  I'm not doing that again.  This is crypto.  

If martians viewed NYC for the first time, they wouldn't understand how the development of America came to be.
A voice, an idea, a mind, somewhere off on the other side of the planet whispered it.  
A butterfly in the amazon flapped its wings an caused a hurricane in Florida.
This is chaos theory irl irt.
I dont care about my mental heath because that's not going to make me happy.
Inner peace will make me happy and wealthy in life.  
Not money.
Knowing that I've "flapped my wings", makes me wealthy and happy.
There is no "professional" because they don't exist.
Anyone can learn from anyone.  We should be learning from each other because we all understand we have a purpose. 
I've discovered mine.  I suggest we all go what we need to do in order to find our passion and inner peace to become wealthy in life.

**Comment by delbonis** [comment] 2021-05-26 04:45
@bernTOAST What's up buddy?  Need some help?

**Comment by Im-Mr-Chris** [comment] 2021-05-26 04:45
i just forked starlink, i didn''t know it was open.  I'm def. going to need help. any and everybody's help

**Comment by bernTOAST** [comment] 2021-05-26 04:46
@delbonis I don't like you. I think you're stupid af when it comes to anything else other than basic coding.. certainly wouldn't listen to any poor life advice from a loser like you

**Comment by delbonis** [comment] 2021-05-26 04:48
@bernTOAST

>I think you're stupid af when it comes to anything else other than basic coding.

Are you sure?  I think you'd like to take me up on my 10 DOGE bet.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 04:48
guys focus cmon

**Comment by bernTOAST** [comment] 2021-05-26 04:49
@delbonis 🤡🎪

**Comment by delbonis** [comment] 2021-05-26 04:49
@Im-Mr-Chris That Starlink repo you forked is from this academic project: http://starlink.eao.hawaii.edu/starlink

**Comment by Im-Mr-Chris** [comment] 2021-05-26 04:50
> @Im-Mr-Chris That Starlink repo you forked is from this academic project: http://starlink.eao.hawaii.edu/starlink

thank you sir

**Comment by floyddcosta** [comment] 2021-05-26 05:04
Here's one schematic architecture of how this could work.

![Space based Digital Asset Network and Exchange v1](https://user-images.githubusercontent.com/18484500/119605169-e419e580-be22-11eb-8dbf-ebdd5c1851a6.jpg)

**Comment by floydd1** [comment] 2021-05-26 05:09
Here's one schematic architecture of how it could work.

![Space based Digital Asset Network and Exchange v1](https://user-images.githubusercontent.com/84830474/119605531-8b971800-be23-11eb-8dac-529fd69c2385.jpg)

**Comment by Im-Mr-Chris** [comment] 2021-05-26 05:22
lol wow!!! this is so sick! maybe im not all that crazy after all lol

**Comment by CryptoTankGirl** [comment] 2021-05-26 05:29
let me know if i can be any help the HarborTeaParty is on board

**Comment by Im-Mr-Chris** [comment] 2021-05-26 05:30
> let me know if i can be any help the HarborTeaParty is on board

haha i was already on it!

**Comment by arthurgervais** [comment] 2021-05-26 06:58
Awesome discussion! Here's another high level how it could look like. To keep Dogecoin secure, the miners need the lowest latency of all network nodes.

![Dogecoin on Starlink](https://user-images.githubusercontent.com/8501292/119616029-69d86980-be00-11eb-869c-a01beeab808d.gif)

**Comment by RFNco** [comment] 2021-05-26 07:28
I can't believe we're going to achieve multi planet payment...

**Comment by RFNco** [comment] 2021-05-26 07:29
Multi-planet payment

**Comment by wzhang878** [comment] 2021-05-26 07:41
This is a blast idea!

**Comment by helleflo1312** [comment] 2021-05-26 08:47
Sounds great.
Does anyone know if Starlink also plans compute nodes in the future?
The fact that this zone does not requires air conditionals is great.
So get the cloud to the literal universe.

I'll be the first one who runs a core node on a starlink virtual machine

**Comment by jjranalli** [comment] 2021-05-26 11:02
Further elaborating on this amazing proposal, I think Starlink is in the ideal position to dramatically decrease the adoption barrier for regular users (i.e. increasing decentralisation) by making it easy for anyone to spin up new nodes with a dedicated product/solution.

Besides improving the bandwidth limit with the relay network, Starlink could go even further and improve the storage limit by shipping such a solution to users with optimised hardware and storage. I'm talking about a buy-sync-mine experience that allows literally anyone to run a node through the Starlink relay network.

Also, I know it's incredibly early to discuss naming but I just want to get it off my chest: I feel like Starchain would be quite appropriate here.

**Comment by AadiPapp** [comment] 2021-05-26 11:22
This is great, mine doge in space

**Comment by apkc-dvsts** [comment] 2021-05-26 11:50
Another thing to use such global satellites network is the ability to avoid the 51% attack from highly centralized clusters. In this case whole planet can be split into cells and there could be an option to define different complexity to each node depending on it's current hash rate. PoW can then be shifted from worker-based to cell-based, saying we have 1000 such cells all over the world, out of those 600 are active and block confirmation needs then consensus of 301 blocks. And internally of each block all the nodes can also have their internal 51% rule but already based on hash rates... 
Sorry, I'm not good at describing this in details, but I believe this is somewhat catchy.
Also this would be a great feature that will have impact in currently rural or inhabitant territories - once it is seen that some cells have less hashing rate complexity - this will bring intestments to that cell to build up new blockchain nodes.

**Comment by jasonwelz** [comment] 2021-05-26 11:53
Why not natively integrate Syntropy (https://www.syntropynet.com/) as some other blockchains plan to (see https://medium.com/syntropynet/syntropy-elrond-partner-to-launch-technical-integration-ca3dd6ebf126). The Syntropy network could include Starlink nodes, and could serve as a layer of the internet that can plug into most/all blockchains, including Doge.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 12:06
I'm still not able to figure out software to hardware. I've been studying starlinks code, but it feels so outdated with its current foundation. Or at least with what's currently available. 

If this is going to happen, wouldn't we need to get the research team behind starlink on board? 

How can we begin to actually approach applying doge source code to sl hardware?

The mention regarding a targeted attack would make starlink makes the network extremely valuable as an asset for those who mass adopt it as it might be something that centralized big tech internet providers do not currently. Or at least from what we know.

**Comment by delbonis** [comment] 2021-05-26 13:52
@helleflo1312

> Does anyone know if Starlink also plans compute nodes in the future?

They have not announced plans to and I doubt that they ever will, as sats are a very highly controlled environment with a constrained compute budget.  Running untrusted code (even in a VM, if the hardware they have even supports that) is a high risk.

@apkc-dvsts

I believe you should re-examine how proof-of-work works, you seem to be misunderstanding.  Splitting up the compute like that decreases the overall security of the network.  The design you propose would also put a high degree of trust in the Starlink infrastructure.

Mining cryptocurrencies in space is an *absurd* idea, for the same reasons as the above reply.  There just isn't the resources available.

@Im-Mr-Chris

>I'm still not able to figure out software to hardware. I've been studying starlinks code, but it feels so outdated with its current foundation. Or at least with what's currently available.

I believe you're mistaken.  The Starlink project that you found is not the same Starlink that you're thinking of.  It's an academic project for working with star charts maintained by an observatory in Hawaii.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 13:55
@delbonis This is very insightful. I'll continue to conduct more osint on the situation. I don't think it can scale with legality around.

**Comment by br0k3NaN** [comment] 2021-05-26 14:04
Don't get me wrong, I would love this idea and see dogecoin running on Starlink but at the same time, this looks very unrealistic. Please correct me if I am wrong, but Starlink has the own goals and roadmap very well defined so I don't see how they could make this happen and for what?

**Comment by Aitare** [comment] 2021-05-26 14:05
A P2P internet via a hotspot router network could be run far more safely and on a needs by needs basis. If E.M. offered an integration API like Algorad has. The broader positioning feeds from our major assets, e.g. Tesla vehicle, Power wall, mobiles and Satellite dish.

**Comment by helleflo1312** [comment] 2021-05-26 15:43
> @helleflo1312
> 
> > Does anyone know if Starlink also plans compute nodes in the future?
> 
> They have not announced plans to and I doubt that they ever will, as sats are a very highly controlled environment with a constrained compute budget. Running untrusted code (even in a VM, if the hardware they have even supports that) is a high risk.

I dont understand your arguement. If I create a google cloud vm (btw they collobarate now with starlink) i can also ein untrusted code in a virtual machine. For that reason there exists microsegmentation and tenants

**Comment by bohuspollak** [comment] 2021-05-26 16:20
What are you smoking?

**Comment by air0key** [comment] 2021-05-26 19:39
如果理论可行 这项工作必须在早期开始与Starlink合作，谁也不知道星链铺设完成以后某些东西是否会变的不可逆，所以现在就把想法给Elon看看吧，可行的话，他一定会支持的。

**Comment by patricklodder** [comment] 2021-05-26 19:41
只是在推特上给他这个网址。

**Comment by Im-Mr-Chris** [comment] 2021-05-26 19:48
> Don't get me wrong, I would love this idea and see dogecoin running on Starlink but at the same time, this looks very unrealistic. Also, Starlink has the own goals and roadmap very well defined so I don't see how they could make this happen and for what? 
> 
> 
> 
> 

This I agree with. We're assuming that starlink would even be open to the community. Their team has been working on this for years. I'm sure they have their own roadmap as well considering the amount of resources their team has. Which in my view is more than just ideas, but real world application and insight as to why their building that tech. 

I still see this as a dream in motion though. Chaos theory in its raw form.

**Comment by Im-Mr-Chris** [comment] 2021-05-26 19:51
> 如果理论可行 这项工作必须在早期开始与Starlink合作，谁也不知道星链铺设完成以后某些东西是否会变的不可逆，所以现在就把想法给Elon看看吧，可行的话，他一定会支持的。
> 
> 

在我看来，这是真的。 我非常有信心，他看到了这个线索，并影响了他脑中一些想法，使他们得以付诸实践。

**Comment by Im-Mr-Chris** [comment] 2021-05-26 19:52
> 只是在推特上给他这个网址。

我不想分散他的注意力。  Twitter就足够了。

**Comment by patricklodder** [comment] 2021-05-26 19:57
> 我不想分散他的注意力。 Twitter就足够了。

但是他可以在这里打断一切吗? 😥

**Comment by metatron1973** [comment] 2021-05-26 20:03
Hey thanks for this post powerful ...

**Comment by Im-Mr-Chris** [comment] 2021-05-26 20:45
> > 我不想分散他的注意力。 Twitter就足够了。
> 
> 
> 
> 但是他可以在这里打断一切吗? 😥
> 
> 
> 我想让他想起英雄所投下的石头。 我不相信他会对我们这样做。 至少这就是我所喂养的。 我认为他已经失去了许多相信他的人，因为他为他们的人生目标和他们热爱的事业带来了价值。 在这方面，我主要是指自己。
> 
> 
> 
> 
> 
> 
> 
> 
>

**Comment by DogeMedwin** [comment] 2021-05-27 03:27
> > 我不想分散他的注意力。 Twitter就足够了。
> 
> 但是他可以在这里打断一切吗? 😥

@Im-Mr-Chris @patricklodder  cant believe that both of you can reply to each other in Chinese!Awesome!

**Comment by Im-Mr-Chris** [comment] 2021-05-27 03:29
> > > 我不想分散他的注意力。 Twitter就足够了。
> 
> > 
> 
> > 但是他可以在这里打断一切吗? 😥
> 
> 
> 
> @Im-Mr-Chris @patricklodder  cant believe that both of you can reply to each other in Chinese!Awesome!

What can I say? The language translation is nearly spot on! I'm sure we can code together like nothing. 

Anyone else testing other languages? I'm having some issues with Turkish to English based off Google translate.

**Comment by DogeMedwin** [comment] 2021-05-27 03:34
> 如果理论可行 这项工作必须在早期开始与Starlink合作，谁也不知道星链铺设完成以后某些东西是否会变的不可逆，所以现在就把想法给Elon看看吧，可行的话，他一定会支持的。

我信他一级他的团队不定时的在这里看着进展，也许我们现在提出的想法，他们早已经在进行中了。既然他已经选择了狗狗币是全球人口，外太空货币，那么他肯定已经在计划，而且是他的性格是快速的，不久的将来，我们绝对会看见好消息。

**Comment by DogeMedwin** [comment] 2021-05-27 03:36
> > > > 我不想分散他的注意力。 Twitter就足够了。
> > 
> > 
> > > 
> > 
> > 
> > > 但是他可以在这里打断一切吗? 😥
> > 
> > 
> > @Im-Mr-Chris @patricklodder  cant believe that both of you can reply to each other in Chinese!Awesome!
> 
> What can I say? The language translation is nearly spot on! I'm sure we can code together like nothing.
> 
> Anyone else testing other languages? I'm having some issues with Turkish to English based off Google translate.

I'm pretty sure there will be multi language here in soon time.

**Comment by kitcateleven** [comment] 2021-05-27 03:43
Oh Im gonna go do it too, from Atlanta!  
Hello friends!

**Comment by usayao** [comment] 2021-05-27 09:23
真希望Elon可以看到这个想法。

**Comment by daijianlin** [comment] 2021-05-27 22:37
Arthur, How about on your project LQD? Unbelievable you gave up your project and ran like a mouse?

**Comment by metatron1973** [comment] 2021-05-28 04:22
It's a perfect integration

**Comment by CryptoTankGirl** [comment] 2021-05-28 05:38
> > > > > 我不想分散他的注意力。 Twitter就足够了。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 但是他可以在这里打断一切吗? 😥
> > > 
> > > 
> > > @Im-Mr-Chris @patricklodder  cant believe that both of you can reply to each other in Chinese!Awesome!
> > 
> > 
> > What can I say? The language translation is nearly spot on! I'm sure we can code together like nothing.
> > Anyone else testing other languages? I'm having some issues with Turkish to English based off Google translate.
> 
> I'm pretty sure there will be multi language here in soon time.

>>> I @CryptoTankGirl am well practiced with having conversations in multiple language use conversations and its pretty simple compared to what one may think.

**Comment by Pepitokitty** [comment] 2021-05-28 23:25
> But is starlink "decentralized"? Otherwise, why build on it?
> Apologies if this off topic but it needs the foundation of complete decentralization.
> In the end if it wasn't, I don't see this as any different than the paper version.

This is exactly what I was thinking. Starlink is centralized and thus is opposed to the fundamentals of cryptocurrency. I don't see a reason to build on a centralized system.

**Comment by patricklodder** [comment] 2021-05-28 23:35
Virtually everything in the world is centralized. The way to use that is to not make any centralized thing a single point of failure. That's why... someone just has to download https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-aarch64-linux-gnu.tar.gz and put it on a couple of satellites. No code changes needed, no posts needed. Just. Do. It.

**Comment by Im-Mr-Chris** [comment] 2021-05-29 00:16
Hmmm...suddenly I got excited over this again. Adding this to my hw.

**Comment by Im-Mr-Chris** [comment] 2021-05-29 01:47
> Hmmm...suddenly I got excited over this again. Adding this to my hw. 
> 
> 
> Edit: checksum please 

Disregard. I've reconsidered by ethics.

**Comment by wzhang878** [comment] 2021-05-29 13:43
> Awesome discussion! Here's another high level how it could look like. To keep Dogecoin secure, the miners need the lowest latency of all network nodes.
> 
> ![Dogecoin on Starlink](https://user-images.githubusercontent.com/8501292/119616029-69d86980-be00-11eb-869c-a01beeab808d.gif)

Pure solar powered mining?

**Comment by TravisCondict** [comment] 2021-06-02 00:19
I have been thinking about this concept and how it's similar to the Helium network.  Can the dogecoin blockchain be integrated with Helium and Starlink?

**Comment by bobdos** [comment] 2021-07-25 12:21
OK, I draw my understanding here:

![mojidoge-dogecoin-space-currency](https://user-images.githubusercontent.com/195643/126898715-485c6ac4-823c-49f7-81ab-8a82f74e5cf4.jpeg)

**Comment by ReverseControl** [comment] 2021-09-01 12:21
@arthurgervais You are encouraged to bring topics worthy of discussion, as is this, to the discussion section rather than the Issue section. I am closing this as off-topic. Feel free to open new discussions on the discussion section.

**Closed by ReverseControl** 2021-09-01 12:21 UTC
Labels: external

**Comment by CryptoTankGirl** [comment] 2021-09-01 15:27
Another item is 👏 🤩 
Checked off and closed an issue! Congrats and thank you to all those that put the coding into everything Doge represents and the possibilities it can hold for the future generations in crypto! We are making history and should all be proud of the work we are collectively doing no matter the size of the task! We are all doge and doge is everything! 

Peace Love and Light to you all who read this!
