### ISSUE TITLE
[bug] Can't open Dogecoin Core in Mac OS Monterey [Version 12.2.1]

### ISSUE THREAD

**Issue by arstagaev** [dogecoin/dogecoin#2929] opened 2022-04-18 19:01 UTC
![image](https://user-images.githubusercontent.com/53790451/163860647-675232e2-ca98-40d7-ad5f-723965999a64.png)
What need to do?:)

# Bug Report

**Current behavior:**
Dont open app

**Expected behavior**
Need open app

**Dogecoin Core version**
Last version: 1.14.5

**Comment by Administratordes** [comment] 2022-04-27 00:22
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by zelongc** [comment] 2022-05-05 14:23
did you try disable your firewall?

**Comment by arstagaev** [comment] 2022-05-05 16:02
> did you try disable your firewall?

yep:)
![image](https://user-images.githubusercontent.com/53790451/166964905-8c9ac8b9-62bf-4d76-9cbe-1a6f88420884.png)

**Comment by zelongc** [comment] 2022-05-06 03:40
em.. idk except shut down all firewall (for example I use bitdefender), and use "open anyway" if there's option available..

**Comment by arstagaev** [comment] 2022-05-08 20:44
> em.. idk except shut down all firewall (for example I use bitdefender), and use "open anyway" if there's option available..

I don't have any another firewalls on my mac

**Comment by FierceSkit** [comment] 2022-06-14 15:27
The Issue seems to be the core-wallet having initially been compiled having macs running intel in mind and only occurs on Mac's running on M1-Architecture but most likely will affect M2 aswell.

After first Installation to the Application folder, the App can't be launched from Launchpad.
The Notification preventing the App from executing, states there would be an Update needed, because the current Version can't be checked for malicious software.


Unfortunately there is no proper fix at the moment, other than circumventing this Process for now.


If the Notification prevents you from running Core-Wallet on M1:

1. Try to open the App from Launchpad.

2. Click "Show in Finder" within the Notification, right-click the Dogecoin Core-App inside the Application folder and launch.

3. The very same Notification will pop up but there's an option to launch it anyway.

4. This should launch the App and Initialisation can take place.


Once launched, there won't be any more Notifications, when launching the App from Launchpad.

From what I can tell, there is no unusual Behaviour in Performance or Power-consumption.

**Comment by patricklodder** [comment] 2022-07-21 01:10
This is now fixed with 1.14.6 - I ran the binary through notarization with a slightly changed signing process, and we've confirmed it to work on both Intel and M1 (with rosetta.)

**Closed by patricklodder** 2022-07-21 01:10 UTC
