### ISSUE TITLE
Transaction Fee Adjustment is broken.  Cannot send more than 1 Doge/kb 

### ISSUE THREAD

**Issue by nikitis** [dogecoin/dogecoin#1691] opened 2021-02-01 17:05 UTC
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

#### If so, please list the steps to reproduce below:
1. Set transaction fee to 10 doge  (Anything above 1)
2. Hit "Send" button, enter passcode to decrypt.
3. On popup summary screen asking "Are you sure you wish to send" it only states 1 Doge will be taken for transaction despite value in step 1 above.  Transaction ID's also report only 1 doge was used.  This is causing 18 hour delays in sending during volatility times.

### Expected behaviour
Tell us what should happen

When I set a custom fee value, or use the recommended value and it shows a value, when I hit send, on the popup summary screen it should show the amount being used towards the transaction fee and actually use it.  

### Actual behaviour
Tell us what happens instead

It is only ever using 1 doge instead on the screen, and verified as only using 1 doge for the transaction in the transaction id browser.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

I believe the GUI pop up screen is accurately displaying the correct value of 1 as that is what it is sending, but the client is not honoring the custom or recommended doge/kb values set manually in the client.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Release 1.14.2  64-Bit   Downloaded from dogecoin.com

### Machine specs:
- OS: Windows 10 20H2
- CPU: AMD 3900x
- RAM: 32GB Trident
- Disk size: 1 TB
- Disk Type (HD/SDD): NVME

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
None that relate to this error.

**Comment by nikitis** [comment] 2021-02-01 17:06
I'd also like to note.  I tested with several other people in the #dogecoin IRC Chatroom on freenode and they confirmed the bug, and asked me to report the bug.

**Comment by codecr** [comment] 2021-02-06 22:56
I am facing the same bug

**Comment by apogay37** [comment] 2021-02-07 20:37
I have same problem.
![1](https://user-images.githubusercontent.com/74876332/107158758-ea2fa780-6994-11eb-8566-32794c3796f0.png)

**Comment by shibe2** [comment] 2021-02-07 20:39
This is a bug. But tell me why are you trying to set a different fee?

**Comment by apogay37** [comment] 2021-02-07 20:44
@shibe2 
Because 1 DOGE fee will take days to process transaction?

**Comment by shibe2** [comment] 2021-02-07 20:53
The fee that Dogecoin Core actually pays is the recommended fee. Your transaction won't have any higher priority if you pay larger fee. If your node is well-connected with the rest of the network, your transaction will be confirmed within minutes with recommended fee. If your node is not well-connected, you can submit your transaction manually, but increasing the fee will not have any effect.

(Note though, if you pay less than recommended fee, your transaction will not be confirmed.)

**Comment by IncognitoJam** [comment] 2021-02-07 21:17
Should fee adjustment be removed altogether from Dogecoin QT? Seems like it causes more confusion when it presents the options to change it.

**Comment by shibe2** [comment] 2021-02-07 21:26
Currently, there is *normally* no reason to use any other fee than recommended. It's good that fee requirement is deterministic. But things may change in the future. At some point, 1 DOGE fee may become high, and we should be ready to change the default policy. I was saying that before, but people disregarded my concerns, thinking that I was dreaming. Maybe now they will listen.

**Comment by Itamal** [comment] 2021-02-09 11:38
When should we hold a wide referendum regarding the 1doge fee? to make sure doge stays competitive as it rises.

**Comment by shibe2** [comment] 2021-02-09 14:33
I think, referendum would not be needed here. Let's discuss it on reddit and in Dogecoin chats. https://redd.it/lg4hp7

**Comment by rnicoll** [comment] 2021-02-09 14:46
Also I need to emphasise - it's not any single group you need to convince, but it's both the wider community and the miners, because if you reduce the fees, you're reducing miner payments, and we have no way of forcing them to accept that.

**Comment by nikitis** [comment] 2021-03-31 13:47
As the original poster.  I've had transactions take 18 hours with 900 peers connected.  (I actually have a proper NAT-PMP (UPnP) set up correctly on my router and my QT client makes good use of it.  It's rare, but I had this happen only during times of high congestion.  In Most networks using a higher fee will put you at a higher priority.  If Doge network isn't programmed to care it won't care, but there is still the issue of longer transaction times during times of high congestion of transaction times like when the coin is spiking and many people are buying and selling.  It is not always as you say that Doge transactions are fast and quick.  It's simply not always true in those times.  

So what solution can we propose?  I'd rather spend a higher fee to be able to snipe a transaction during high congestion times rather than lose far more money on a trade due to congestion?

I'd say program it to care about the fee spent, but put a warning stating that in most times other than high congestion times 1 doge is all that is needed for a quick and snappy transaction, are you sure you wish to spend more doge?  And leave it up to the user to decide.

**Comment by nikitis** [comment] 2021-03-31 13:52
Doge can still be cheap compared to other coins, but we do need a way to pay for a priority transaction during times of congestion if the user so chooses to do so.

**Comment by shibe2** [comment] 2021-03-31 15:57
>In Most networks using a higher fee will put you at a higher priority.

It's not applicable to your case. Miners in Dogecoin and other currencies do prioritize transactions based on fee, but your transaction probably could not reach any miner's node. Relay nodes don't prioritize transactions because they don't collect fees. There was a proposal to give fraction of fees to relay nodes to incentivize fast delivery to miners, but I don't know if any cryptocurrency has implemented it.

>So what solution can we propose? I'd rather spend a higher fee to be able to snipe a transaction during high congestion times rather than lose far more money on a trade due to congestion?
>I'd say program it to care about the fee spent

Here is a general proposed scheme: https://www.microsoft.com/en-us/research/wp-content/uploads/2012/06/bitcoin.pdf I don't think we can implement it any time soon, but this is something to ponder about for the future.

>there is still the issue of longer transaction times during times of high congestion of transaction times like when the coin is spiking and many people are buying and selling. It is not always as you say that Doge transactions are fast and quick. It's simply not always true in those times.

This is a correct observation, but it's not relevant to this issue "Transaction Fee Adjustment is broken". Please open a new issue. We are already working on improvements to Dogecoin P2P network, but it may be useful to have a place to discuss solutions and track the progress. Dogecoin network is already in much better shape, and should another spike of activity happen, it will not have such dramatic impact.

>Doge can still be cheap compared to other coins, but we do need a way to pay for a priority transaction during times of congestion if the user so chooses to do so.

I think, such prioritization would not work. The problem is, however programmed, nodes are not prepared for network congestion. They struggle to timely propagate anything at all, no matter how much fees are involved. Fee sharing in theory could incentivize building of stronger network, but in practice fees may not provide enough incentive during normal operation, and spikes happen unexpectedly.

**Comment by ReverseControl** [comment] 2021-08-18 13:09
@nikitis All transactions cost 1 DOGE. There is no incentive for nodes or miners to favor any transaction more than other, they all cost the same.

Having said that. Fees are in the process of being reduced, and the bug you allude has partly been addressed already (#2446 ). 

@patricklodder @rnicoll @michilumin  We can close this.

**Comment by patricklodder** [comment] 2021-08-21 03:06
The good news is that this was actually fixed with #2446 and the QT wallet now allows you to set the fee as high or as low as you wish.

I'll close this now.

**Closed by patricklodder** 2021-08-21 03:06 UTC
