### ISSUE TITLE
can some one limit the supply of coin ?

### ISSUE THREAD

**Issue by vijaychowthri** [dogecoin/dogecoin#1963] opened 2021-05-18 02:50 UTC
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin or wallet recovery please use one of the various communities:

* [Dogeducation on reddit](https://www.reddit.com/r/dogeducation/)
* [Discord](https://discord.com/invite/dogecoin)

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by GiverofMemory** [comment] 2021-05-18 05:40
Why?

**Comment by bot66** [comment] 2021-05-18 11:48
Why?

**Comment by BruceHunter** [comment] 2021-05-18 15:32
1) The supply is set at a specific rate of inflation.
2) Increasing the supply provides more coins, so that there is plenty of liquidity of Doge in the system for the population.
Also, users lose coins over time, so the supply needs to increase over time. Imagine if a large portion of users lost coins and it was limited. Yes, the price increases b/c of scarcity, but the volume will decrease b/c users won't be able to get it to use for currency. The lack of coins is bad!
3) Increasing the supply actually will lower volatility over time as the volume of usage increases. (Hypothesis).

I personally disagree with this issue of limiting the supply of coins for the following items above.

Debate is welcome

**Comment by vijaychowthri** [comment] 2021-05-18 15:52
I agree, 

1) Probably we would require some  AI to manage the logical supply.

2) With out demand if we keeps supply inflow , that would inflate badly.

Can we get more economics background folks thoughts on this regards. !?

**Comment by Spicymelange** [comment] 2021-05-18 16:10
In regards to providing liquidity (case #2), as long as a money is divisible enough, prices will adjust inline with the goods demanded by holders of Doge no matter the supply.  There will be enough Doge to go around.

Increasing the supply of coins punishes good stewards of Doge and incentivizes them to hold other, "harder" monies.

**Comment by BruceHunter** [comment] 2021-05-18 19:54
Sending 1 coin vs 0.0001 coin divisible is annoying and confusing to most people. Keep it simple.
Maybe remove the divisible feature.

**Comment by veryscience** [comment] 2021-05-18 20:06
I made a website where you can easily track the Doge Yearly Supply Inflation as of today. As you can see the inflation is 3.86% and dropping every day. That doesn't include burned or lost coins either.

https://veryscience.github.io/dogeinflation/

**Comment by vijaychowthri** [comment] 2021-05-18 20:09
Inflation rate is less than USA (4.2%) good to hear , thanks

**Comment by bernTOAST** [comment] 2021-05-18 21:55
Close this.

**Comment by AbcSxyZ** [comment] 2021-05-18 22:50
## Goal of limited supply

This question about limiting the supply is coming again and again. The goal behind it is **deflation**,
to reproduce the behavior of bitcoin with his 21 millions limited caps.

By the time, the value of your money increase, and your wallet also. Sounds cool.

## Deflation in economy

There is a lot a theory behind economy, and I'm not an economist, but nowadays
*deflation is seen as a threat*, they speak about **deflationary spiral**.

The problem with deflation is it prevent you to spend. Because the price go up by the time,
you will wait before making purchase. It's probably what's happening with bitcoin.

Some impact of deflation on economy :
- Decrease investment.
- Decrease production & consumption
- Decrease hiring & increase unemployment
- Decrease salary

*Mechanically with the increase of unemployment, **poverty** and **violence** will increase.*

In actual monetary policy they try to avoid deflation (at the opposite they try to avoid hyper-inflation). For example in Europe, the inflation goal of the central bank is 2 %.

## Deflation for a currency

With my current understanding of economic theories (I do not have knowledge to go further them), no currency should expect to be deflationary.
Bitcoin is good to be a store of value, but specifically because of his deflation model, it will probably
never be used as day-to-day currency. It will have too much negative incentive for economic agents.
[*I'm sometime wondering if it's good to call bitcoin a cryptocurrency (cryptoactif is better ?) because it's perhaps a bad idea to use it as a currency*]

Deflation is good to see your wallet increase, from and individual perspective, but probably bad from a macroeconomic point of view, the collective perspective.
But it seems so obvious & basic, I don't understand why so much crypto are going in this way.

P.S.: From my point of view, Dogecoin look deflationary (at least for the moment). A part of me will prefer to wait an increase of his value instead of spending it, and that's possibly bad !

**Closed** 2021-05-20 09:58 UTC
