### ISSUE TITLE
Feature request: Add transaction code field ala XLM and XRP

### ISSUE THREAD

**Issue by Drael64** [dogecoin/dogecoin#1809] opened 2021-03-30 04:58 UTC
As dogecoin is an emerging payment method, a transaction code for transactions may help facilitate this usage, for online merchants etc. Not a coder, just think this is potentially a good idea.

**Comment by shibe2** [comment] 2021-03-30 06:20
If I understand it correctly, you want to include some data, like unique number, in a transaction. On the Dogecoin protocol level you can do that already with OP_RETURN. This is rarely being used, because it is not needed. In Dogecoin, payments are uniquely identified by recipient address. Sellers / merchants typically create a new address for each payment, so when they receive dogecoins, they know what good / service / order is paid for. Exchanges and other services where users can deposit Dogecoin create unique address for each user.

In the past, Monero wallets typically had only one receiving address. To identify the purpose of transaction, an arbitrary number could be optionally included. Nowadays Monero wallets can have multiple receiving addresses, and identifying number is no longer needed. It is recommended to use a new receiving address for each new purpose.

I personally discourage Dogecoin address reuse. I.e. you should create a new receiving address every time. Some wallet software and services, like MultiDoge and DogeChain, don't have a convenient way to manage many addresses. This is what needs to be improved.

**Comment by Drael64** [comment] 2021-03-30 08:01
Yes, a transaction code. Would it not make more sense, having or using such a code, instead of infinitely creating wallets? 

Like if one was a business, taking doge as a payment, wouldn't a code be easier to track, to use for accounting purposes than 50,000 receiving addresses? 

You'd need an additional layer of software to remember all the transactions by receiving address, and link them up with your invoicing, ordering system in terms of individual orders. Whereas with just a code that can be ascribed to the order number itself, that's not needed. 

Likewise if you had a friend you wanted to send money to, if they don't have a particular address, you have to ask them every time you send doge for their new address. It's far more convenient to have a constant address than an ever changing one.

**Comment by shibe2** [comment] 2021-03-30 08:18
>Would it not make more sense, having or using such a code, instead of infinitely creating wallets?

You confuse wallets and addresses. One wallet can have as many addresses as needed. Good wallet software makes it easy to manage many addresses. Typically, users don't need to know how many addresses their wallets have. A new address is always available when needed. Addresses can be labeled, so whenever coins are received, a description of payment can be shown, not just some number.

>You'd need an additional layer of software to remember all the transactions by receiving address, and link them up with your invoicing, ordering system in terms of individual orders. Whereas with just a code that can be ascribed to the order number itself, that's not needed. You can literally just put the order number right into the chain, and displayed directly on your wallet.

You still need to remember what order number corresponds to what's ordered and for whom. That is, you need a database with a record for each order. You can add Dogecoin address to that record. Additional layer is not needed.

Also, receiving addresses in HD wallets are numbered, so you don't even need to store the address if you don't want to. Instead, you can derive unique Dogecoin address from order number and your wallet's xpub.

>Likewise if you had a friend you wanted to send money to, if they don't have a particular address, you have to ask them every time you send doge for their new address.

In this case it is OK to use the same address. The friend uses one new address from their wallet, labels it with my name and gives the address to me once. Whenever I want to give them money, I send to that address, and their wallet will show that coins came from me. But they should use a unique address for each of *their* friends.

**Comment by shibe2** [comment] 2021-03-30 08:47
Bitcoin and by heritage Dogecoin was created as *anonymous* system. That is, the sender and recipient of transaction are not identified. An address is an identifier of payment purpose, not an identifier of a party of the transaction. (Though coins are *traceable* and often it is possible to later identify the parties in the transaction, but not always.)

>It's far more convenient to have a constant address than an ever changing one.

It indeed might be a little more convenient to use one address per person, but not by far. Because BTC and DOGE were like that from the beginning, most software is created with that in mind, and it handles these aspects efficiently. The problem is that some users don't understand what Dogecoin addresses are. But as soon as they learn how to use wallets properly, they won't have problems with multiple addresses.

**Comment by Drael64** [comment] 2021-03-30 10:25
If  you have a friend as I've said, and their wallet changes address, it doesn't matter how the software handles it, you still need to bug them for their new address even time you sent them doge. Kind impractical.  

Likewise it would be far easier to deal with account records as a business, if you used a txn field linking an order number or account, rather than multiple wallets, at least from the point of not needing an engineered order processing system that tabulates that with order numbers.

IMO If you want an economic driver system to be well implemented, you can't very well have every account number changing all the time. 

I understand privacy is a concern to some, and part of the philosophy of using cryptocurrency (or was). But being a currency is also part of the philosophy of cryptocurrency, and for that purpose, I believe it should be as practical as possible.  As it stands, changing wallets is optional, not built in behavior. And I can't imagine a world, where that exists in every element of our economy.

**Comment by shibe2** [comment] 2021-03-30 11:44
>If you have a friend as I've said, and their wallet changes address, it doesn't matter how the software handles it, you still need to bug them for their new address even time you sent them doge.

That's not the case. Wallet can receive coins on any of it's addresses.

>Likewise it would be far easier to deal with account records as a business, if you used a txn field linking an order number or account, rather than multiple wallets, at least from the point of not needing an engineered order processing system that tabulates that with order numbers.

>As it stands, changing wallets is optional, not built in behavior.

Again, you confuse wallets and addresses. Read my previous explanations. Or better yet, learn how to use Dogecoin wallets properly, and your concerns will be resolved. What wallet software do you use?

>Like what if you were paying rent every week, or making an automatic payment? Being able to have a known point to transfer to, is not something I believe any form of electronic money can do without, if it's to actually operate in the place of fiat in some significant manner.

New address it's not required for recurring payments, but sometimes new addresses are used anyway for purposes of accounting. As a rule of thumb, there should be one to one correspondence between Dogecoin address and purpose of payment. When the payment is for the same thing, the same address can be used.

For example, when you pay for additional week of ongoing service, the provider can give you the same Dogecoin address that was used previously. That address is unique for customer and kind of service, so when coins are received on that address, the provider knows which service to prolong.

On the other hand, a provider can send you bills for each period of service separately, then it makes sense to use unique address for each bill. It's up to provider which way of billing they want. As a consumer, you send coins to whatever address they give you, it doesn't matter for you whether it's the same or different address.

**Comment by Drael64** [comment] 2021-03-30 20:32
I use coinomi. But I find the constant changing of receive and send addresses to be annoying. Just an extra thing, I wouldn't have to do with a bank account number.

**Comment by shibe2** [comment] 2021-03-31 10:17
Here are some instructions for Coinomi.

### Sending Dogecoin between friends

Gifts, loans, repayment. For this scenario you don’t need separate payments for particular things.

Open your main Dogecoin wallet, go to “Receive” page. Here you should see a new Dogecoin address. Touch action menu button (vertical dots) and select “Edit label”. Enter your friend’s name and touch “Save”. Then give that address to your friend. This needs to be done once. Don’t give this address to anybody else.

For another friend, use a new address and label it with that other friend’s name. If you need to give unique addresses to several people at once, use menu item “New address” for each subsequent person.

Whenever you receive coins from one of your friends, the wallet will display their name, so you know who sent.

If a friend asks for your Dogecoin address again, go to “Receive” page, touch “Previous addresses”, find the address with your friend’s name and touch it. Now you can give them the same address that they used before. If for some reason you want to use a new address for the same friend, just use a new address and label it with the same name or a name plus ordinal number.

When you need to send coins to your friend, ask them for Dogecoin address. Go to “Send” page, paste or scan their address and send coins. On “Balance” page touch the transaction that sends coins to your friend. On transaction details page you should see your friend’s address. Touch it. Touch pencil icon to edit label. Enter your friend’s name and touch “Save”.

Next time you need to send coins to the same friend, go to “Send” page, type your friend’s name into “To” field. You should see their address, touch it to use.

If at some point a friend wants to receive coins from you on a different address, first edit the label of their old address. Touch hamburger menu button (stack of horizontal lines), select “Address Book”. Find and touch your friend’s old address. Touch pencil button to edit label. Mark the address as old, for example, add to word “old” or ordinal number to the label. After that send the coins to the new address and set a label the same way as you did the first time.

### Accepting Dogecoin payments

In this scenario you use unique address for each payment.

If you receive payments only occasionally, you can use one wallet for everything. If you have a business, it may be better to use a separate subwallet for business-related payments.

*Optional:* To create a new subwallet, touch “+” button on “Overview” page. Select “Add coins”. Select Dogecoin and touch “+” button. Enter password. You should see your new Dogecoin subwallet on the overview page. Long-touch it and then touch pencil button to edit its name. Enter a new name, for example the name of your business and touch “Save”. Then you can use business wallet for accepting payments and your first Dogecoin wallet for personal stuff. The new wallet will initially have zero balance. To transfer coins between subwallets you send them the same way as with unrelated wallets.

To accept a payment, go to “Receive” page. Here you should see a new address. Touch action menu button (vertical dots) and select “Edit label”. If the address already has a label, i.e. it was used for an invoice that was not paid yet, click “Cancel” and use “New address” menu item to get unique address. For the label, enter order or invoice number or description, so that it will clearly identify the purpose of payment.

You can have multiple outstanding invoices with different customers. When you receive coins, the wallet will show which one is paid.

### Accepting recurring payments

This scenario is similar to receiving coins from friends. Label addresses with customer’s and/or service’s name or number. When you accept the first payment use a new address. For subsequent payments, go to “Previous addresses” list and find the address that was used previously for the same customer/service.

**Comment by shibe2** [comment] 2021-03-31 10:21
>But I find the constant changing of receive addresses to be annoying.

It's not that your old address is changing, it's that you should use a new address for a new purpose. The old address remains in your wallet and you can use it again in cases where it's appropriate.

This is not annoying if you understand it and make use of it. I hope that my instructions will help you with that.

**Comment by Drael64** [comment] 2021-03-31 21:38
Sounds like it's not set and forget, but you have to actively re-enable previous addresses. Which is still an extra step you don't have to do with fiat.

**Comment by shibe2** [comment] 2021-03-31 22:32
What do you mean by "re-enable previous addresses"?

**Comment by Drael64** [comment] 2021-04-01 01:16
According to the description you posted, in order to receive from a previously used address, you need to "go to “Receive” page, touch “Previous addresses”, find the address with your friend’s name and touch it. Now you can give them the same address that they used before"

Unlike a bank account, where you can simply maintain a fixed address without these extra steps and complication. The same seems to apply to a recurring payment. 

"Label addresses with customer’s and/or service’s name or number. When you accept the first payment use a new address. For subsequent payments, go to “Previous addresses” list and find the address that was used previously for the same customer/service."

**Comment by shibe2** [comment] 2021-04-01 01:34
>According to the description you posted, in order to receive from a previously used address, you need to "go to “Receive” page...

No, my instruction does not say "in order to receive from a previously used address". It doesn't even make sense. You receive not *from* your address, but *to* your address.

What instruction says is:

>Whenever you receive coins from one of your friends, the wallet will display their name, so you know who sent.

**Comment by Drael64** [comment] 2021-04-01 07:34
If you read back in the thread, you'll find that's a direct copy and paste.

**Comment by shibe2** [comment] 2021-04-01 10:09
Well you said that first, then I included it in my message as a quote of your message and I'm saying that it's not true.

Anyway, all your arguments in favor of additional transaction identifier are based on misunderstanding of how wallets work and how Dogecoin payments are processed. The problem of accepting multiple payments was solved even before Dogecoin was created, and solutions work well.

The only concern there may be that managing multiple addresses may be confusing for some users at first. But that's not a valid reason to use payment identifiers, which would only add to confusion and be a source of user errors.

Currently, a payer needs to enter Dogecoin address and amount. You propose that he would also need to enter some additional identifier, which is strictly worse experience.

A payee needs to learn how to manage multiple addresses. In your proposal he would need to learn how to manage multiple payment identifiers. It doesn't make experience better or worse.

In total its 1:0 for not changing the way it works.

Also, any confusion here is caused by misconceptions that new users may have when they come from systems that work in a different way or if someone taught them incorrectly. People that I introduced to Dogecoin don't have a problem with it. For beginners it's enough to know that their receiving address is on "Receive" page. Most don't care whether it's the same address or a new address every time. To those who do care, I just explain how it works.

**Comment by Drael64** [comment] 2021-04-01 10:21
"Well you said that first, then I included it in my message as a quote of your message and I'm saying that it's not true."

No. It was me quoting your instructions for coinomi. It's right there above. It's not a quote from me at all. 

"The only concern there may be that managing multiple addresses may be confusing for some users at first. But that's not a valid reason to use payment identifiers, which would only add to confusion and be a source of user errors."

Not from how I understand what you posted about coinomi. It appears to be additional steps, beyond what you'd use for conventional finance, to achieve the same result. If someone wants to send you money, without requesting a new address from you, you need to go in and activate it. It cannot be done passively. 

"Currently, a payer needs to enter Dogecoin address and amount. You propose that he would also need to enter some additional identifier, which is strictly worse experience."

Debatable I think. XLM and XRP both do this (have an optional transactions feild), and I've never heard a soul complain about it. 

"A payee needs to learn how to manage multiple addresses. In your proposal he would need to learn how to manage multiple payment identifiers. It doesn't make experience better or worse."

Except that's what's already familiar to everyone, so no one needs to learn it.  

"Also, any confusion here is caused by misconceptions that new users may have when they come from systems that work in a different way"

That's what makes something intuitive, or a learning curve. Perhaps someone else could weigh in on this now? It's ultimately not about what you or I think.

**Comment by shibe2** [comment] 2021-04-01 11:11
>No. It was me quoting your instructions for coinomi. It's right there above. It's not a quote from me at all.

The search for "in order to receive from a previously used address" shows that it first appeared in your message. And as I said, it's nonsense, no matter who said it first.

>If someone wants to send you money, without requesting a new address from you, you need to go in and activate it.

That's not true.

>Debatable I think.

What I'm saying is: as for the payer experience, all other things being equal, requiring to enter one more thing is strictly worse than not requiring it. It's a matter of fact.

>I've never heard a soul complain about it

You somehow missed all the cases where users forgot to enter the identifier or made an error in it. I'm sure those are numerous. By contrast, if you make a typo in Dogecoin address, wallet software will detect it and will not send coins until you correct the error.

>Except that's what's already familiar to everyone, so no one needs to learn it.

I don't think so. If you ask a random person how they would accept payments, most would just say that they would give their identifier (bank account number, user name etc.). They would not immediately see that they would need a way to keep track of concurrent orders etc.

>That's what makes something intuitive, or a learning curve.

I agree that there is a learning curve, and we should think about how to improve the experience for new users. But as I said, payment identifiers don't improve it in any way.

**Comment by Drael64** [comment] 2021-04-01 12:19
"The search for "in order to receive from a previously used address" shows that it first appeared in your message. And as I said, it's nonsense, no matter who said it first."

Ah, I see where you getting caught up. it's a distraction though. The instructions specifically state you need to enable that previous wallet address. So, again, there's no way to do this as a receiver, passively. The sender must get your interaction. That's the important part. 

"That's not true."

That's what you posted though, about coinomi. 

"You somehow missed all the cases where users forgot to enter the identifier or made an error in it"

Does that actually happen though? Copy and paste can be done even on a phone. Can be made mindlessly easy with a copy button. 

"What I'm saying is: as for the payer experience, all other things being equal, requiring to enter one more thing is strictly worse than not requiring it. It's a matter of fact."

Not if you want to send to someone, without their interaction in recreating a previous receiver address, as per the instructions you posted.  

"I don't think so. If you ask a random person how they would accept payments, most would just say that they would give their identifier (bank account number, user name etc.). They would not immediately see that they would need a way to keep track of concurrent orders etc."

They do this with bank account payments every day. It's more familiar that multiple wallet addresses. That's the part they would not immediately see. 

"But as I said, payment identifiers don't improve it in any way."

I think you've made your opinion clear.

**Comment by shibe2** [comment] 2021-04-01 13:34
>The instructions specifically state you need to enable that previous wallet address.

What do you mean by "enable"? I never said something like that.

>Does that actually happen though?

Yes. One can copy the address but forget to copy the identifier. Or incorrectly select it while copying and miss one digit.

>They do this with bank account payments every day.

Not many people have experience with receiving payments from *customers*. When they get involved, they either:

* use an existing system that manages invoices and track payments,
* learn or invent a way to do it properly,
* do it in a simple/stupid way.

I saw that some small businesses don't use order identifiers. They match payments by customer's and sender's name which is provided by the bank or payment system. In cases where names don't match (for example, somebody pays for somebody else), they request a confirmation from the customer or payer. Obviously, that would not work for anonymous cryptocurrency.

>I want to pay you doge. You are currently busy and have a rotating wallet address. Or maybe I don't have your contact details at all.

With any system you need to know the destination (account number, user name, or Dogecoin address) in order to send money. How do you imagine sending money without getting that information from the recipient? And I need to know what you pay for, which also requires interaction.

Though if I want to receive anonymous donations without any personal interaction whatsoever, I can put my Dogecoin address somewhere. Is that what you mean?

>Let's say I want to find a particular order number, on my wallet, for a particular product.

The wallet shows whatever label you entered for the address. It can be order number, customer name, or whatever information you need for identifying the payment. If the wallet is integrated with your invoicing/billing system, everything can be processed automatically.

**Comment by Drael64** [comment] 2021-04-01 13:57
"Is that what you mean?"

Well an example would be my former employer, who no longer has my contact details, or any means to contact me, but had my bank account number from previous payments, and sent me a missing payment. No contact, no context, just money sent. 

"And I need to know what you pay for, which also requires interaction."

You can just put what the payment is for, in the payment details when you do the bank transfer. 

With a bank account number, receiving cash can be entirely passive once your address is known, or a single payment is made.

**Comment by shibe2** [comment] 2021-04-01 15:47
>Well an example would be my former employer, who no longer has my contact details, or any means to contact me, but had my bank account number from previous payments, and sent me a missing payment. No contact, no context, just money sent.

There is interaction and context. You gave the employer your account number for a particular purpose, for paying salary. This is the interaction. They could pay you timely or late, that doesn't change the procedure.

For Dogecoin salary you can use "recurring payment" procedure. Use a new address and label it with employer's and/or job's name. Give that address to the employer. Whenever you will receive salary, the wallet will show you that it is the salary.

>You can just put what the payment is for, in the payment details when you do the bank transfer.

In Dogecoin you can attach some information with OP_RETURN. This feature is rarely used because it's not how business is done. Customers normally pay *after* they ordered something.

Theoretically, you can combine payment and ordering system in one service. Imagine ATM where you can select some good or service, enter all the required details and insert cash to pay for the order. Then again, cash payment is done after ordering.

Dogecoin is a payment system, it doesn't have ordering functionality, so this use case is out of scope.

>Or it might be for no specific reason, like a gift, or part of a long owed repayment.

That is covered by "sending Dogecoin between friends" and "anonymous donations" cases.

**Comment by Drael64** [comment] 2021-04-02 00:13
"For Dogecoin salary you can use "recurring payment" procedure. Use a new address and label it with employer's and/or job's name. Give that address to the employer. Whenever you will receive salary, the wallet will show you that it is the salary."

But in this case I have to anticipate being paid more than once, yes? If I did not, the person would not be able to pay me without requiring my interaction. 

What if I wanted to set up an all purpose, static address to receive dogecoin from anyone? Just so that people always have the ability to pay me doge, without my needing to anticipate each persons desire to do so? 

And then, I also wanted to give those people the ability to confer the intention behind their transaction? Again without anticipating their intent. 

"In Dogecoin you can attach some information with OP_RETURN. This feature is rarely used because it's not how business is done."

What exactly is this field intended for, what can it contain, and is it ever used?

**Comment by shibe2** [comment] 2021-04-02 00:37
>What if I wanted to set up an all purpose, static address to receive dogecoin from anyone? Just so that people always have the ability to pay me doge, without my needing to anticipate each persons desire to do so?

This is covered by "anonymous donations" case.

>And then, I also wanted to give those people the ability to confer the intention behind their transaction?

The best way to do this is to let them confer their intention first, then give unique address associated with that intention.

>What exactly is this field intended for, what can it contain, and is it ever used?

This is an opcode, not a field, but basically you can include up to about 80 bytes of arbitrary data with the transaction.

**Comment by Drael64** [comment] 2021-04-02 01:03
So you are saying there's no way to receive payments, labelled by intent/purpose, without specifically anticipating that specific intent.

**Comment by shibe2** [comment] 2021-04-02 07:41
>But what is it's actual intended use?

Putting data on the block chain and burning coins. There are several use cases which I think are not important for Dogecoin. But people are doing these things anyway, so there is a clean way to do it.

**Comment by ReverseControl** [comment] 2021-09-02 22:05
This has turned into a discussion. I am closing this issue. I encourage the discussion of this topic over in the discussion section: https://github.com/dogecoin/dogecoin/discussions.

**Closed by ReverseControl** 2021-09-02 22:05 UTC
