### ISSUE TITLE
checksum changed

### ISSUE THREAD

**Issue by Thermi** [dogecoin/dogecoin#1372] opened 2017-05-25 14:48 UTC
Hi,

I am the maintainer of the dogecoin-qt package on the AUR[1].
Back when I made the PKGBUILD in November of 2015, the SH-256 checksum of the v1.10 tarball was 
"2c279a7ee425b3706ce635c74a27fd813ac3605a37f6f13e63775ec311f90f7c".
Now, it is "e392f4142819fdab313ba921af53fdbd2cf6ee8965d237d0cb5cda8a52c97084". Why did it change? What was changed?

Kind regards,
Thermi

[1] https://aur.archlinux.org/packages/dogecoin-qt

**Comment by langerhans** [comment] 2017-05-25 15:20
So I just downloaded tarballs from both the 1.10.0 tag and master which are based on the same commit. Both show a different sha256sum, yet when I unpack them and binary compare every single file they are identical. I can confirm tho that the sha256sum you see on 1.10.0 is the same I see right now.   

Looking around, this seems to caused by github preiodically clearing their cache of tarballs and regenerating them when they get requested again. So if no one downloaded that archive recently enough, it gets recreated and thus the checksum changes. One reference here: https://lists.macports.org/pipermail/macports-dev/2016-April/032864.html

**Comment by 5685C4A059D5** [comment] 2017-05-27 14:17
I just downloaded the archive and it's `d1e17dbfbad8f87f3cf97259e95dc07e1c1efda38d54a9d0d880b4be024f0fc2` now.
I can imagine people getting confused whenever they try to install the package.

**Comment by JRWR** [comment] 2017-05-27 16:49
Yep, I bet it changes due to timestamps and other metadata

**Comment by DomT4** [comment] 2017-05-29 01:53
GitHub recently updated their `git` backend apparently, which smashed a whole bunch of checksums, see [the fun we had at Homebrew](https://github.com/Homebrew/homebrew-core/pull/13792). This seems likely related.

**Comment by langerhans** [comment] 2017-05-29 07:03
@Thermi Is this enough info for you to change the checksums? If so, please close the issue :) Thank you again for bringing this up.

**Comment by Thermi** [comment] 2017-06-06 20:58
@langerhans Sorry for not checking this for so long. Well, the answer is satisfactory if we can permanently fix the issue. I maintain the PKGBUILD for dogecoin-qt on the AUR and habe sha256 checksums for all the files. If the checksums change every couple of weeks, the checksums are pointless and unnecessary work.

**Closed** 2018-12-31 20:13 UTC
