### ISSUE TITLE
[bug] [1.14.4-dev] Qt keyboard detection issue /w german keyboard layout

### ISSUE THREAD

**Issue by fmhc** [dogecoin/dogecoin#2338] opened 2021-06-24 02:37 UTC
# Bug Report

**Current behavior:**
When installing the 1.14.4-dev on Ubuntu 20.04 with german keyboard layout, the dogecoin-qt starts / loads and syncs correctly but throws an error on the console and the keyboard input can not be used.

**Expected behavior**
The keyboard layout is correctly loaded from Qt and the user is able to use the keyboard to type into form fields and use buttons.

**Steps to reproduce:**
1. Install fresh Ubuntu 20.04 LTS Desktop VM
2. Set the keyboard layout / language to German (standard) while setup
3. snap install dogecoin-unofficial --channel=edge
4. dogecoin-unofficial.qt
5. open a form (e.g. send) and try typing in an address with the keyboard = not working

**Screenshots**
![image](https://user-images.githubusercontent.com/3387385/123192893-152e1a00-d4a4-11eb-8957-9cf806265b33.png)

**Dogecoin Core version**
Version 1.14.4-dev PR 1904: https://github.com/dogecoin/dogecoin/pull/1904
probably same results with all 1.14.4-dev as all based on Qt v5.7.1

**Machine specs**
- OS: Ubuntu 20.04 LTS Desktop 
- CPU: 4 cores VM
- RAM: 4 GB
- Disk size: 100 GB
- Disk Type (HD/SDD): HDD VMI

**Extra information**
related issue in Qt v.5.7.1 (we're using that in 1.14.4-dev): https://github.com/conda-forge/qt-feedstock/issues/104
we need to upgrade to a newer version of Qt. See discussion in https://github.com/dogecoin/dogecoin/pull/1904 also

Newer version of Qt shoudl be changed here: https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/depends/packages/qt.mk
will try that out with qt 5.15 or 5.12, I'm currently confused about the structure of the newer versions on the download archive server...

**Comment by fmhc** [comment] 2021-06-24 09:52
https://github.com/katzenmalen/dogecoin/commit/9d138a75a2078532cdde52ef913c95490215eb56
![image](https://user-images.githubusercontent.com/3387385/123241812-c010f900-d4e1-11eb-9af2-1242b244ada4.png)
waiting for the rpc tests but i guess that should be fine. Tested with building on Ubuntu 20.04. / german keyboard layout and locale.

I found some other warnings during the build process which have already been open issues, https://github.com/dogecoin/dogecoin/issues/1488 and this one the same & with a proposed solution. Thinking about reopening them and solving.

For the proposed changes, how can we audit these sources the best, where we have checksums in the game?

**Comment by fmhc** [comment] 2021-06-27 03:46
![image](https://user-images.githubusercontent.com/3387385/123532142-ebc2f780-d70a-11eb-99f3-70966dbfddf9.png)
What is this?

**Comment by fmhc** [comment] 2021-06-27 03:53
![image](https://user-images.githubusercontent.com/3387385/123532210-9b986500-d70b-11eb-8b73-1bc6758d0385.png)
https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk

https://github.com/bitcoin/bitcoin/commit/d1d1cc983146ece950430da78ebae6f502913a53
from what i can see here in the commit, we probably should go to v.5.12.11 as my initial thought was while comparing folder structures and finding out about Qt stepping back a bit from open source strategy
![image](https://user-images.githubusercontent.com/3387385/123532234-cedaf400-d70b-11eb-8a79-25f332dbccc5.png)

**Comment by fmhc** [comment] 2021-06-27 04:15
> ![image](https://user-images.githubusercontent.com/3387385/123532142-ebc2f780-d70a-11eb-99f3-70966dbfddf9.png)
> What is this?

ah found out its the depends Makefile with a FALLBACK_DOWNLOAD_PATH

![image](https://user-images.githubusercontent.com/3387385/123532279-25483280-d70c-11eb-9d37-a89efa9fa55e.png)


this would be a point to end up at cherry picking i guess, but its a long way through the bitcoin commits. https://github.com/bitcoin/bitcoin/commit/fa416cea84d8f1528fc7ecf9a04654aae75ac3f5#diff-0d7e256978e78897b774581dad22102138ce4ba46aa07faaef1ae6fc6178aad4

**Comment by rnicoll** [comment] 2021-07-14 20:31
Also relevant here: https://github.com/dogecoin/dogecoin/pull/2365

**Comment by ReverseControl** [comment] 2021-08-16 05:05
@patricklodder Given #2365 , as pointed out by @rnicoll above, could we move this one for the next release as well along with #2365 as it seems to me the solution to that would also resolve this one?

**Comment by patricklodder** [comment] 2021-08-16 07:31
That's a question for @rnicoll because he assigned this to himself :-)

**Comment by ReverseControl** [comment] 2021-08-16 07:34
@rnicoll See comment above. please.

**Comment by ReverseControl** [comment] 2021-08-17 10:27
@rnicoll Could you please take a look at this?

**Comment by rnicoll** [comment] 2021-08-17 23:35
@ReverseControl Sorry for some reason I seem to not get half the GitHub notifications.

We had a nightmare of a time getting the Qt update to work on every platform, I want to push ahead with getting the current batch of improvements into 1.14.5, but yes aware we need to come back to this.

**Comment by ReverseControl** [comment] 2021-08-17 23:48
@rnicoll I am on the Dogecoin Discord server, my Email and tweeter are also on my git profile. You can reach me directly and can coordinate better. Same for @patricklodder  @michilumin.

**Comment by patricklodder** [comment] 2021-09-28 21:17
@fmhc would it be possible for you to check out the results of #2595 and let us know if that fixes your issue?

**Comment by polska333** [comment] 2021-09-29 15:34
Can anybody help me all my ghost coin went missing after I upgraded to the
new wallet like I was told to I don't know what's going on I'm disabled I'm
connected to a machine 16 hours a day I died once already and now all my
dose coin is missing that's the only thing that was keeping my mind off my
disability I'm going to die again it could be days could be months could be
years hopefully he is but I am scared and now all my dose going is going I
don't know what happened

**Comment by patricklodder** [comment] 2021-11-01 22:05
Closing this as #2595 was confirmed on other keyboard layouts. if this problem persists, please let us know.

**Closed by patricklodder** 2021-11-01 22:05 UTC
